## Install

In [1]:
!apt-get install -y poppler-utils
!pip install typhoon-ocr pdf2image beautifulsoup4 pandas

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 186 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.12 [186 kB]
Fetched 186 kB in 1s (213 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.12_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.12) ...
Setting up poppler-utils (22.02.0-2ubuntu0.12) ...
Processing triggers for man-db (2.10.2-1) ...
Collecting typhoon-ocr
  Downloading typhoon_ocr-0.4.1-py3-none-any.whl.metadata (4.7 kB)
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting ftfy (from typhoon-ocr)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting pypdf (from typhoon-ocr)
  Downloading pypdf-6.10.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from typhoon-ocr) (11.3.0)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (from typhoon-ocr) (2.32.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy->typhoon-ocr) (0.6.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai->typhoon-ocr) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai->typhoon-ocr) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai->typhoon-ocr) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai->typhoon-ocr) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai->typhoon-ocr) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai->typhoon-ocr) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai->typhoon-ocr) (4.67.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai->typhoon-ocr) (3.13)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai->typhoon-ocr) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai->typhoon-ocr) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->typhoon-ocr) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai->typhoon-ocr) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai->typhoon-ocr) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai->typhoon-ocr) (0.4.2)
Downloading typhoon_ocr-0.4.1-py3-none-any.whl (17 kB)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.6 MB/s eta 0:00:00
Downloading pypdf-6.10.2-py3-none-any.whl (336 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.3/336.3 kB 9.2 MB/s eta 0:00:00
Installing collected packages: pypdf, pdf2image, ftfy, typhoon-ocr
Successfully installed ftfy-6.3.1 pdf2image-1.17.0 pypdf-6.10.2 typhoon-ocr-0.4.1

## Import / API Key

In [2]:
import os
import re
import json
import pandas as pd
from bs4 import BeautifulSoup
from pdf2image import convert_from_path
import typhoon_ocr

os.environ["TYPHOON_API_KEY"] = "sk-t9KG8HcqEVppXtX0vlMK329ZWTAO0gvKP7hvjlEm7ssGjikM"

## Upload Files

PDFs (1 pdf per 1 voting station)

**Page layout:**


- `page[0]` -> constituency
- `page[1]` -> ignore
- `page[2], [3], [4]` -> party_list
- `page[5]` -> ignore

In [3]:
import os, zipfile
from google.colab import files

uploaded = files.upload()

DATA_ROOT = "data"
os.makedirs(DATA_ROOT, exist_ok=True)

for fname, data in uploaded.items():
    if fname.lower().endswith('.zip'):
        zip_path = os.path.join(DATA_ROOT, fname)
        with open(zip_path, 'wb') as f:
            f.write(data)
        with zipfile.ZipFile(zip_path, 'r') as z:
            z.extractall(DATA_ROOT)
        os.remove(zip_path)
        print(f"Extracted zip: {fname} → {DATA_ROOT}/")
    else:
        # fallback: single PDFs place at data/<filename>
        with open(os.path.join(DATA_ROOT, fname), 'wb') as f:
            f.write(data)

# Create subdistrict_pdf_map: {subdistrict_name: [pdf_path, ...]}
# Refer folder 1st layer of DATA_ROOT as sub-district name
subdistrict_pdf_map = {}
for entry in sorted(os.listdir(DATA_ROOT)):
    entry_path = os.path.join(DATA_ROOT, entry)
    if not os.path.isdir(entry_path):
        continue
    # sub-district name = 1.คูซอด' --> 'คูซอด'
    subdistrict_name = entry.split('.', 1)[-1] if '.' in entry else entry
    pdfs = []
    for root, dirs, files_in in os.walk(entry_path):
        dirs.sort()
        for fn in sorted(files_in):
            if fn.lower().endswith('.pdf'):
                pdfs.append(os.path.join(root, fn))
    if pdfs:
        subdistrict_pdf_map[subdistrict_name] = pdfs

if not subdistrict_pdf_map:
    # fallback: if upload PDF directly without folder structure
    loose_pdfs = sorted([os.path.join(DATA_ROOT, f)
                         for f in os.listdir(DATA_ROOT)
                         if f.lower().endswith('.pdf')])
    if loose_pdfs:
        subdistrict_pdf_map['unknown'] = loose_pdfs

print(f"Subdistricts found: {len(subdistrict_pdf_map)}")
for sd, paths in subdistrict_pdf_map.items():
    print(f"sub-district {sd}: {len(paths)} PDF(s)")

Saving data.zip to data.zip
Extracted zip: data.zip → data/
Subdistricts found: 11
sub-district ชุดที่1: 1 PDF(s)
sub-district ชุดที่10: 1 PDF(s)
sub-district ชุดที่11: 1 PDF(s)
sub-district ชุดที่2: 1 PDF(s)
sub-district ชุดที่3: 1 PDF(s)
sub-district ชุดที่4: 1 PDF(s)
sub-district ชุดที่5: 1 PDF(s)
sub-district ชุดที่6: 1 PDF(s)
sub-district ชุดที่7: 1 PDF(s)
sub-district ชุดที่8: 1 PDF(s)
sub-district ชุดที่9: 1 PDF(s)

## Pre-DataFrame: 57 Parties

In [ ]:
PARTY_NAMES = [
    "ไทยทรัพย์ทวี",
    "เพื่อชาติไทย",
    "ใหม่",
    "มิติใหม่",
    "รวมใจไทย",
    "รวมไทยสร้างชาติ",
    "พลวัต",
    "ประชาธิปไตยใหม่",
    "เพื่อไทย",
    "ทางเลือกใหม่",
    "เศรษฐกิจ",
    "เสรีรวมไทย",
    "รวมพลังประชาชน",
    "ท้องที่ไทย",
    "อนาคตไทย",
    "พลังเพื่อไทย",
    "ไทยชนะ",
    "พลังสังคมใหม่",
    "สังคมประชาธิปไตยไทย",
    "ฟิวชัน",
    "ไทรวมพลัง",
    "ก้าวอิสระ",
    "ปวงชนไทย",
    "วิชช์นใหม่",
    "เพื่อชีวิตใหม่",
    "คลองไทย",
    "ประชาธิปัตย์",
    "ไทยก้าวหน้า",
    "ไทยภักดี",
    "แรงงานสร้างชาติ",
    "ประชากรไทย",
    "ครูไทยเพื่อประชาชน",
    "ประชาชาติ",
    "สร้างอนาคตไทย",
    "รักชาติ",
    "ไทยพร้อม",
    "ภูมิใจไทย",
    "พลังธรรมใหม่",
    "กรีน",
    "ไทยธรรม",
    "แผ่นดินธรรม",
    "กล้าธรรม",
    "พลังประชารัฐ",
    "โอกาสใหม่",
    "เป็นธรรม",
    "ประชาชน",
    "ประชาไทย",
    "ไทยสร้างไทย",
    "ไทยก้าวใหม่",
    "ประชาอาสาชาติ",
    "พร้อม",
    "เครือข่ายชาวนาแห่งประเทศไทย",
    "ไทยพิทักษ์ธรรม",
    "ความหวังใหม่",
    "ไทยรวมไทย",
    "เพื่อบ้านเมือง",
    "พลังไทยรักชาติ",
]

PARTY_INDEX = {name: idx for idx, name in enumerate(PARTY_NAMES)}
assert len(PARTY_NAMES) == 57, f"Expected 57 parties, got {len(PARTY_NAMES)}"
print(f"Pre-DataFrame ready: {len(PARTY_NAMES)} พรรค")

Pre-DataFrame ready: 57 พรรค

## Helper Functions

In [9]:
CONSTITUENCY_PAGES = {0}
PARTY_LIST_PAGES   = {2, 3, 4}
SKIP_PAGES         = {1, 5}

def extract_meta(ocr_text):
    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = ocr_text.translate(thai_to_arabic)

    def grab(pattern):
        m = re.search(pattern, text)
        if not m:
            return None

        val = m.group(1)
        if not val:
            return None

        val = val.strip()
        return int(val) if val.isdigit() else None

    return {
        "eligible": grab(r"ผู้มีสิทธิเลือกตั้งตามบัญชี.*?จำนวน\s*(\d+)"),
        "show_up": grab(r"ผู้มีสิทธิเลือกตั้งที่มาแสดงตน.*?จำนวน\s*(\d*)"),
        "prepared_cards": grab(r"บัตรเลือกตั้งที่ได้รับจัดสรร.*?จำนวน\s*(\d+)"),
        "used_cards": grab(r"บัตรเลือกตั้งที่ใช้.*?จำนวน\s*(\d+)"),
        "good_cards": grab(r"บัตรดี.*?จำนวน\s*(\d+)"),
        "bad_cards": grab(r"บัตรเสีย.*?จำนวน\s*(\d+)"),
        "no_vote_cards": grab(r"ไม่เลือกบัญชีรายชื่อ.*?จำนวน\s*(\d+)"),
        "remaining_cards": grab(r"บัตรเลือกตั้งที่เหลือ.*?จำนวน\s*(\d+)"),
    }


def clean_score(score_text):
    if not score_text:
        return None
    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    score_text = score_text.translate(thai_to_arabic).strip()

    if score_text in ('-', '–', '—', ''):
        return 0
    match = re.search(r"\d+", score_text)
    return int(match.group()) if match else None


def is_summary_row(cols):
    if not cols:
        return True
    first = cols[0].translate(str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")).strip()
    return not re.match(r"^\d+$", first)


def extract_constituency_rows(ocr_text):
    soup = BeautifulSoup(ocr_text, "html.parser")
    rows = []
    for table in soup.find_all("table"):
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if len(cols) < 4:
                continue
            if is_summary_row(cols):
                continue
            rows.append({
                "หมายเลข"    : cols[0],
                "ชื่อ-นามสกุล": cols[1],
                "พรรค"       : cols[2],
                "คะแนน"      : clean_score(cols[3]),
            })
    return rows


def extract_party_list_scores(ocr_text):
    soup = BeautifulSoup(ocr_text, "html.parser")
    scores = {}
    for table in soup.find_all("table"):
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if len(cols) < 3:
                continue
            if is_summary_row(cols):
                continue
            num_str = cols[0].translate(str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")).strip()
            if not re.match(r"^\d+$", num_str):
                continue
            party_num = int(num_str)
            if party_num < 1 or party_num > 57:
                continue
            score = clean_score(cols[2])
            # นับทุก party ที่อ่าน party_num ได้ ไม่ว่า score จะ None หรือไม่
            # None หมายถึง OCR อ่านไม่ออกจริงๆ (ไม่ใช่แค่ '-') fallback 0
            scores[party_num - 1] = score if score is not None else 0
    return scores

print("Helper functions defined.")

Helper functions defined.

# Pipeline: Party List

Loop over all PDFs and read page[2-4]

In [ ]:
party_unit_rows = []
debug_rows = []

for subdistrict_name, pdf_paths_sd in subdistrict_pdf_map.items():
    # outer loop: all sub-district
    print("\n" + "#"*60)
    print(f" ตำบล: {subdistrict_name}  ({len(pdf_paths_sd)} หน่วย)")
    print("#"*60)

    for pdf_path in pdf_paths_sd:
        # inner loop: all units in sub-district
        pdf_filename = os.path.basename(pdf_path) # e.g. '7.pdf'
        print("\n" + "="*60)
        print(f" PDF: {pdf_path}")
        print("="*60)

        pages = convert_from_path(pdf_path, 300)
        print(f" Total pages: {len(pages)}")

        ocr_results = {}

        for i, page in enumerate(pages):
            if i in SKIP_PAGES:
                print(f"[Page {i}] SKIPPED")
                continue
            if i not in PARTY_LIST_PAGES:
                print(f"[Page {i}] SKIPPED (constituency pipeline)")
                continue

            img_path = f"page_{i}.jpg"
            page.save(img_path, "JPEG")

            try:
                result = typhoon_ocr.ocr_document(img_path)
                ocr_results[i] = result
                print(f"[Page {i}] Done")
            except Exception as e:
                print(f"[Page {i}] Error: {e}")
                ocr_results[i] = ""

        unit_scores = [0] * 57
        pages_read = 0
        meta = {}
        page_entries = {}  # for debug df

        print("\n")
        for page_idx in sorted(ocr_results.keys()):
            ocr_text = ocr_results[page_idx]

            # for debug
            print("="*60)
            print(f"\nRaw content from page {page_idx}: \n")
            print(ocr_text)

            if page_idx == 2:
                meta = extract_meta(ocr_text)

            scores = extract_party_list_scores(ocr_text)
            for idx, score in scores.items():
                unit_scores[idx] += score

            page_entries[page_idx] = len(scores) # for debug df
            print(f"\n[Page {page_idx}] party scores read: {len(scores)} entries\n")
            pages_read += 1

        total_score = sum(unit_scores)

        if pages_read == 3:
            status = "COMPLETE"
        else:
            status = f"only {pages_read}/3 pages read"

        print(f"\nmeta: {meta}")
        print(f"total score: {total_score} | {status}")

        # sub-district name comes from folder name, not OCR
        # unit = A.pdf (e.g. '7.pdf' --> 7)
        try:
            unit_num = int(pdf_filename.split('.')[0])
        except ValueError:
            unit_num = pdf_filename  # fallback if filename is not a number

        row = {
            "source_pdf"      : pdf_path,
            "ตำบล"            : subdistrict_name,
            "หน่วยเลือกตั้ง"  : unit_num,
            "pages_read"      : pages_read,
            **meta
        }
        for idx, name in enumerate(PARTY_NAMES):
            row[name] = unit_scores[idx]

        party_unit_rows.append(row)

        debug_rows.append({
            "sub-district"  : subdistrict_name,
            "unit"          : unit_num,
            "page 2 entries": page_entries.get(2, 0),
            "page 3 entries": page_entries.get(3, 0),
            "page 4 entries": page_entries.get(4, 0),
            "total entries" : sum(page_entries.values()),
        })

print("\n" + "="*60)
print(f" TOTAL units processed: {len(party_unit_rows)}")

Streaming output truncated to the last 5000 lines.
 Total pages: 6
[Page 0] SKIPPED (constituency pipeline)
[Page 1] SKIPPED
[Page 2] Done
[Page 3] Done
[Page 4] Done
[Page 5] SKIPPED


============================================================

Raw content from page 2:

ส.ส. ๕/๑๘ (บช)
สีขาว

รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อ

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อของหน่วยเลือกตั้งที่ 12 หมู่ที่ 12 ตำบล/แขวง/เทศบาล ทุ่งสว่าง อำเภอ/เขต วังเหนือ เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของหน่วยเลือกตั้งดังกล่าว ดังนี้
๑. จำนวนผู้มีสิทธิเลือกตั้ง
๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 173 คน (หนึ่งร้อยเจ็ดสิบสาม)
๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 104 คน (หนึ่งร้อยสี่)
๒. จำนวนบัตรเลือกตั้ง
๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 180 บัตร (หนึ่งร้อยแปดสิบ)
๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 104 บัตร (หนึ่งร้อยสี่)
๒.๒.๑ บัตรดี จำนวน 98 บัตร (เก้าสิบแปด)
๒.๒.๒ บัตรเสีย จำนวน 5 บัตร (ห้า)
๒.๒.๓ บัตรที่ไม่เลือกบัญชีรายชื่อของพรรคการเมืองใด จำนวน 1 บัตร (หนึ่ง)
๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 76 บัตร (เจ็ดสิบหก)
๓. จำนวนคะแนนที่พรรคการเมืองแต่ละพรรคได้รับเรียงตามลำดับหมายเลขของบัญชีรายชื่อของพรรคการเมือง

<table><tr><td>หมายเลขของบัญชีรายชื่อ<br/>ของพรรคการเมือง</td><td>ชื่อ<br/>พรรคการเมือง</td><th colspan="2">ได้คะแนน<br/>(ให้กรอกทั้งตัวเลขและตัวอักษร)</th></tr><tr><td>1</td><td>ไทยทรัพย์ทวี</td><td>0</td><td>(ศูนย์)</td></tr><tr><td>2</td><td>เพื่อชาติไทย</td><td>0</td><td>(ศูนย์)</td></tr><tr><td>3</td><td>ใหม่</td><td>1</td><td>(หนึ่ง)</td></tr><tr><td>4</td><td>มิติใหม่</td><td>0</td><td>(ศูนย์)</td></tr><tr><td>5</td><td>รวมใจไทย</td><td>3</td><td>(สาม)</td></tr><tr><td>6</td><td>รวมไทยสร้างชาติ</td><td>1</td><td>(หนึ่ง)</td></tr><tr><td>7</td><td>พลวัต</td><td>1</td><td>(หนึ่ง)</td></tr><tr><td>8</td><td>ประชาธิปไตยใหม่</td><td>0</td><td>(ศูนย์)</td></tr><tr><td>9</td><td>เพื่อไทย</td><td>43</td><td>(สี่สิบสาม)</td></tr><tr><td>10</td><td>ทางเลือกใหม่</td><td>2</td><td>(สอง)</td></tr></table>

[Page 2] party scores read: 10 entries

============================================================

Raw content from page 3:

ส.ส. ๕/๑๘(บช)
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)
<page_number>- ๒ -</page_number><table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>11</td><td>เศรษฐกิจ</td><td>2 ( ส.ส. )</td></tr><tr><td>12</td><td>เสรีรวมไทย</td><td>1 ( หนึ่ง )</td></tr><tr><td>13</td><td>รวมพลังประชาชน</td><td>0 ( คน )</td></tr><tr><td>14</td><td>ท้องที่ไทย</td><td>0 ( คน )</td></tr><tr><td>15</td><td>อนาคตไทย</td><td>0 ( คน )</td></tr><tr><td>16</td><td>พลังเพื่อไทย</td><td>0 ( คน )</td></tr><tr><td>17</td><td>ไทยชนะ</td><td>0 ( คน )</td></tr><tr><td>18</td><td>พลังสังคมใหม่</td><td>0 ( คน )</td></tr><tr><td>19</td><td>สังคมประชาธิปไตยไทย</td><td>0 ( คน )</td></tr><tr><td>20</td><td>พิวซัน</td><td>0 ( คน )</td></tr><tr><td>21</td><td>ไทรวมพลัง</td><td>0 ( คน )</td></tr><tr><td>22</td><td>ก้าวอิสระ</td><td>0 ( คน )</td></tr><tr><td>23</td><td>ปวงชนไทย</td><td>1 ( หนึ่ง )</td></tr><tr><td>24</td><td>วิชช์นใหม่</td><td>0 ( คน )</td></tr><tr><td>25</td><td>เพื่อชีวิตใหม่</td><td>0 ( คน )</td></tr><tr><td>26</td><td>คลองไทย</td><td>0 ( คน )</td></tr><tr><td>27</td><td>ประชาธิปัตย์</td><td>1 ( หนึ่ง )</td></tr><tr><td>28</td><td>ไทยก้าวหน้า</td><td>0 ( คน )</td></tr><tr><td>29</td><td>ไทยภักดี</td><td>0 ( คน )</td></tr><tr><td>30</td><td>แรงงานสร้างชาติ</td><td>0 ( คน )</td></tr><tr><td>31</td><td>ประชากรไทย</td><td>0 ( คน )</td></tr><tr><td>32</td><td>ครูไทยเพื่อประชาชน</td><td>0 ( คน )</td></tr><tr><td>33</td><td>ประชาชาติ</td><td>0 ( คน )</td></tr><tr><td>34</td><td>สร้างอนาคตไทย</td><td>0 ( คน )</td></tr></table>

[Page 3] party scores read: 24 entries

============================================================

Raw content from page 4:

ส.ส. ๕/๑๘(บซ)
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><td>ได้คะแนน<br/>(ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>35</td><td>รักชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>36</td><td>ไทยพร้อม</td><td>1 (หนึ่ง)</td></tr><tr><td>37</td><td>ภูมิใจไทย</td><td>27 (ยี่สิบเจ็ด)</td></tr><tr><td>38</td><td>พลังธรรมใหม่</td><td>1 (หนึ่ง)</td></tr><tr><td>39</td><td>กรีน</td><td>0 (ศูนย์)</td></tr><tr><td>40</td><td>ไทยธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>41</td><td>แผ่นดินธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>42</td><td>กล้าธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>43</td><td>พลังประชารัฐ</td><td>0 (ศูนย์)</td></tr><tr><td>44</td><td>โอกาสใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>45</td><td>เป็นธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>46</td><td>ประชาชน</td><td>10 (สิบ)</td></tr><tr><td>47</td><td>ประชาไทย</td><td>0 (ศูนย์)</td></tr><tr><td>48</td><td>ไทยสร้างไทย</td><td>3 (สาม)</td></tr><tr><td>49</td><td>ไทยก้าวใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>50</td><td>ประชาอาสาชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>51</td><td>พร้อม</td><td>0 (ศูนย์)</td></tr><tr><td>52</td><td>เครือข่ายชาวนาแห่งประเทศไทย</td><td>0 (ศูนย์)</td></tr><tr><td>53</td><td>ไทยพิทักษ์ธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>54</td><td>ความหวังใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>55</td><td>ไทยรวมไทย</td><td>0 (ศูนย์)</td></tr><tr><td>56</td><td>เพื่อบ้านเมือง</td><td>0 (ศูนย์)</td></tr><tr><td>57</td><td>พลังไทยรักชาติ</td><td>0 (ศูนย์)</td></tr><tr><td colspan="2">รวมคะแนนทั้งสิ้น</td><td>98 (เก้าสิบแปด)</td></tr></table>

[Page 4] party scores read: 23 entries


meta: {'eligible': 173, 'show_up': 104, 'prepared_cards': 180, 'used_cards': 104, 'good_cards': 98, 'bad_cards': 5, 'no_vote_cards': 1, 'remaining_cards': 76}
total score: 98 | COMPLETE

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่13/13.pdf
============================================================
 Total pages: 6
[Page 0] SKIPPED (constituency pipeline)
[Page 1] SKIPPED
[Page 2] Done
[Page 3] Done
[Page 4] Done
[Page 5] SKIPPED


============================================================

Raw content from page 2:

ส.ส. ๕/๑๘ (บช)
สีขาว

# ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)

## รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อ

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2567 เป็นวันเลือกตั้ง นั้น

บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อของหน่วยเลือกตั้งที่ 13 หมู่ที่ 13 ตำบล/แขวง/เทศบาล ยุ่งสว่าง อำเภอ/เขต วังนิ่ม เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของหน่วยเลือกตั้งดังกล่าว ดังนี้

๑. จำนวนผู้มีสิทธิเลือกตั้ง
    ๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 222 คน ( สองร้อยยี่สิบสอง )
    ๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 125 คน ( หนึ่งร้อยยี่สิบห้า )

๒. จำนวนบัตรเลือกตั้ง
    ๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 220 บัตร ( สองร้อยยี่สิบบัตร )
    ๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 125 บัตร ( หนึ่งร้อยยี่สิบห้าบัตร )
    ๒.๒.๑ บัตรดี จำนวน 122 บัตร ( หนึ่งร้อยยี่สิบสองบัตร )
    ๒.๒.๒ บัตรเสีย จำนวน 1 บัตร ( หนึ่งบัตร )
    ๒.๒.๓ บัตรที่ไม่เลือกบัญชีรายชื่อของพรรคการเมืองใด จำนวน 2 บัตร ( สองบัตร )
    ๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 95 บัตร ( เก้าสิบห้า )

๓. จำนวนคะแนนที่พรรคการเมืองแต่ละพรรคได้รับเรียงตามลำดับหมายเลขของบัญชีรายชื่อของพรรคการเมือง

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><th colspan="2">ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</th></tr><tr><td>1</td><td>ไทยทรัพย์ทวี</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td>2</td><td>เพื่อชาติไทย</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td>3</td><td>ใหม่</td><td>1</td><td>( หนึ่ง )</td></tr><tr><td>4</td><td>มิติใหม่</td><td>6</td><td>( ศูนย์ )</td></tr><tr><td>5</td><td>รวมใจไทย</td><td>3</td><td>( สาม )</td></tr><tr><td>6</td><td>รวมไทยสร้างชาติ</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td>7</td><td>พลวัต</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td>8</td><td>ประชาธิปโดยใหม่</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td>9</td><td>เพื่อไทย</td><td>81</td><td>( สามสิบเจ็ด )</td></tr><tr><td>10</td><td>ทางเลือกใหม่</td><td>1</td><td>( หนึ่ง )</td></tr></table>

[Page 2] party scores read: 10 entries

============================================================

Raw content from page 3:

ส.ส. ๕/๑๘(บช)
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)
<page_number>- ๒ -</page_number><table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><td>ได้คะแนน<br/>(ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>11</td><td>เศรษฐกิจ</td><td>A ( ส )</td></tr><tr><td>12</td><td>เสรีรวมไทย</td><td>O ( ศูนย์ )</td></tr><tr><td>13</td><td>รวมพลังประชาชน</td><td>O ( ศูนย์ )</td></tr><tr><td>14</td><td>ท้องที่ไทย</td><td>O ( ศูนย์ )</td></tr><tr><td>15</td><td>อนาคตไทย</td><td>O ( ศูนย์ )</td></tr><tr><td>16</td><td>พลังเพื่อไทย</td><td>O ( ศูนย์ )</td></tr><tr><td>17</td><td>ไทยชนะ</td><td>O ( ศูนย์ )</td></tr><tr><td>18</td><td>พลังสังคมใหม่</td><td>O ( ศูนย์ )</td></tr><tr><td>19</td><td>สังคมประชาธิปไตยไทย</td><td>O ( ศูนย์ )</td></tr><tr><td>20</td><td>ฟิวชัน</td><td>O ( ศูนย์ )</td></tr><tr><td>21</td><td>ไทรวมพลัง</td><td>O ( ศูนย์ )</td></tr><tr><td>22</td><td>ก้าวอิสระ</td><td>O ( ศูนย์ )</td></tr><tr><td>23</td><td>ปวงชนไทย</td><td>O ( ศูนย์ )</td></tr><tr><td>24</td><td>วิชชั่นใหม่</td><td>O ( ศูนย์ )</td></tr><tr><td>25</td><td>เพื่อชีวิตใหม่</td><td>O ( ศูนย์ )</td></tr><tr><td>26</td><td>คลองไทย</td><td>1 ( หนึ่ง )</td></tr><tr><td>27</td><td>ประชาธิปัตย์</td><td>O ( ศูนย์ )</td></tr><tr><td>28</td><td>ไทยก้าวหน้า</td><td>O ( ศูนย์ )</td></tr><tr><td>29</td><td>ไทยภักดี</td><td>O ( ศูนย์ )</td></tr><tr><td>30</td><td>แรงงานสร้างชาติ</td><td>O ( ศูนย์ )</td></tr><tr><td>31</td><td>ประชากรไทย</td><td>O ( ศูนย์ )</td></tr><tr><td>32</td><td>ครูไทยเพื่อประชาชน</td><td>O ( ศูนย์ )</td></tr><tr><td>33</td><td>ประชาชาติ</td><td>O ( ศูนย์ )</td></tr><tr><td>34</td><td>สร้างอนาคตไทย</td><td>O ( ศูนย์ )</td></tr></table>

[Page 3] party scores read: 24 entries

============================================================

Raw content from page 4:

ส.ส. ๕/๑๘(บช)
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)
ส.ส. ๕/๑๘(บช)

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><td>ได้คะแนน<br/>(ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>35</td><td>รักชาติ</td><td>๐ ( ศูนย์ )</td></tr><tr><td>36</td><td>ไทยพร้อม</td><td>๖ ( ศูนย์ )</td></tr><tr><td>37</td><td>ภูมิใจไทย</td><td>๕๕ ( ห้าสิบห้า )</td></tr><tr><td>38</td><td>พลังธรรมใหม่</td><td>๒ ( สอง )</td></tr><tr><td>39</td><td>กรีน</td><td>๐ ( ศูนย์ )</td></tr><tr><td>40</td><td>ไทยธรรม</td><td>๐ ( ศูนย์ )</td></tr><tr><td>41</td><td>แผ่นดินธรรม</td><td>๑ ( หนึ่ง )</td></tr><tr><td>42</td><td>กล้าธรรม</td><td>๐ ( ศูนย์ )</td></tr><tr><td>43</td><td>พลังประชารัฐ</td><td>๐ ( ศูนย์ )</td></tr><tr><td>44</td><td>โอกาสใหม่</td><td>๐ ( ศูนย์ )</td></tr><tr><td>45</td><td>เป็นธรรม</td><td>๐ ( ศูนย์ )</td></tr><tr><td>46</td><td>ประชาชน</td><td>๑๖ ( สิบหก )</td></tr><tr><td>47</td><td>ประชาไทย</td><td>๐ ( ศูนย์ )</td></tr><tr><td>48</td><td>ไทยสร้างไทย</td><td>๐ ( ศูนย์ )</td></tr><tr><td>49</td><td>ไทยก้าวใหม่</td><td>๐ ( ศูนย์ )</td></tr><tr><td>50</td><td>ประชาอาสาชาติ</td><td>๐ ( ศูนย์ )</td></tr><tr><td>51</td><td>พร้อม</td><td>๐ ( ศูนย์ )</td></tr><tr><td>52</td><td>เครือข่ายชาวนาแห่งประเทศไทย</td><td>๐ ( ศูนย์ )</td></tr><tr><td>53</td><td>ไทยพิทักษ์ธรรม</td><td>๐ ( ศูนย์ )</td></tr><tr><td>54</td><td>ความหวังใหม่</td><td>๐ ( ศูนย์ )</td></tr><tr><td>55</td><td>ไทยรวมไทย</td><td>๐ ( ศูนย์ )</td></tr><tr><td>56</td><td>เพื่อบ้านเมือง</td><td>๐ ( ศูนย์ )</td></tr><tr><td>57</td><td>พลังไทยรักชาติ</td><td>๑ ( หนึ่ง )</td></tr><tr><td colspan="2">รวมคะแนนทั้งสิ้น</td><td>๑๒๒ ( หนึ่งร้อยยี่สิบสอง )</td></tr></table>

[Page 4] party scores read: 23 entries


meta: {'eligible': 222, 'show_up': 125, 'prepared_cards': 220, 'used_cards': 125, 'good_cards': 122, 'bad_cards': 1, 'no_vote_cards': 2, 'remaining_cards': 95}
total score: 174 | COMPLETE

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่14/14.pdf
============================================================
 Total pages: 6
[Page 0] SKIPPED (constituency pipeline)
[Page 1] SKIPPED
[Page 2] Done
[Page 3] Done
[Page 4] Done
[Page 5] SKIPPED


============================================================

Raw content from page 2:

ส.ส. ๕/๑๘ (บช)
สีขาว

# ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)

## รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อ

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 28 เดือน กุมภาพันธ์ พ.ศ. 2569 เป็นวันเลือกตั้ง นั้น

บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อของหน่วยเลือกตั้งที่ หมู่ที่ ตำบล/แขวง/เทศบาล อำเภอ/เขต เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของหน่วยเลือกตั้งดังกล่าว ดังนี้

๑. จำนวนผู้มีสิทธิเลือกตั้ง
    ๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 210 คน (สองร้อยสิบ)
    ๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 163 คน (หนึ่งร้อยหกสิบสาม)
๒. จำนวนบัตรเลือกตั้ง
    ๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 200 บัตร (สองร้อย)
    ๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 163 บัตร (หนึ่งร้อยหกสิบสาม)
    ๒.๒.๑ บัตรดี จำนวน 156 บัตร (หนึ่งร้อยห้าสิบหก)
    ๒.๒.๒ บัตรเสีย จำนวน 7 บัตร (เจ็ด)
    ๒.๒.๓ บัตรที่ไม่เลือกบัญชีรายชื่อของพรรคการเมืองใด จำนวน 0 บัตร (ศูนย์)
    ๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 37 บัตร (สามสิบเจ็ด)
๓. จำนวนคะแนนที่พรรคการเมืองแต่ละพรรคได้รับเรียงตามลำดับหมายเลขของบัญชีรายชื่อของพรรคการเมือง

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>ไทยทรัพย์ทวี</td><td>0 (ศูนย์)</td></tr><tr><td>2</td><td>เพื่อชาติไทย</td><td>2 (สอง)</td></tr><tr><td>3</td><td>ใหม่</td><td>2 (สอง)</td></tr><tr><td>4</td><td>มิติใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>5</td><td>รวมใจไทย</td><td>5 (ห้า)</td></tr><tr><td>6</td><td>รวมไทยสร้างชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>7</td><td>พลวัต</td><td>1 (หนึ่ง)</td></tr><tr><td>8</td><td>ประชาธิปไตยใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>9</td><td>เพื่อไทย</td><td>67 (หกสิบเจ็ด)</td></tr><tr><td>10</td><td>ทางเลือกใหม่</td><td>0 (ศูนย์)</td></tr></table>

[Page 2] party scores read: 10 entries

============================================================

Raw content from page 3:

ส.ส. ๕/๑๘(บข)
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)
<page_number>- ๒ -</page_number><table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>11</td><td>เศรษฐกิจ</td><td>b (หก)</td></tr><tr><td>12</td><td>เสรีรวมไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>13</td><td>รวมพลังประชาชน</td><td>0 (ศูนย์)</td></tr><tr><td>14</td><td>ท้องที่ไทย</td><td>0 (ศูนย์)</td></tr><tr><td>15</td><td>อนาคตไทย</td><td>0 (ศูนย์)</td></tr><tr><td>16</td><td>พลังเพื่อไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>17</td><td>ไทยชนะ</td><td>0 (ศูนย์)</td></tr><tr><td>18</td><td>พลังสังคมใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>19</td><td>สังคมประชาธิปไตยไทย</td><td>0 (ศูนย์)</td></tr><tr><td>20</td><td>ฟิวชัน</td><td>0 (ศูนย์)</td></tr><tr><td>21</td><td>ไทรวมพลัง</td><td>0 (ศูนย์)</td></tr><tr><td>22</td><td>ก้าวอิสระ</td><td>1 (หนึ่ง)</td></tr><tr><td>23</td><td>ปวงชนไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>24</td><td>วิชชั่นใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>25</td><td>เพื่อชีวิตใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>26</td><td>คลองไทย</td><td>0 (ศูนย์)</td></tr><tr><td>27</td><td>ประชาธิปัตย์</td><td>0 (ศูนย์)</td></tr><tr><td>28</td><td>ไทยก้าวหน้า</td><td>0 (ศูนย์)</td></tr><tr><td>29</td><td>ไทยภักดี</td><td>0 (ศูนย์)</td></tr><tr><td>30</td><td>แรงงานสร้างชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>31</td><td>ประชากรไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>32</td><td>ครูไทยเพื่อประชาชน</td><td>0 (ศูนย์)</td></tr><tr><td>33</td><td>ประชาชาติ</td><td>1 (หนึ่ง)</td></tr><tr><td>34</td><td>สร้างอนาคตไทย</td><td>0 (ศูนย์)</td></tr></table>

[Page 3] party scores read: 24 entries

============================================================

Raw content from page 4:

ส.ส. ๕/๑๘(บช)
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อ พรรคการเมือง</td><td>ได้คะแนน<br/>(ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>35</td><td>รักชาติ</td><td>1 (หนึ่ง)</td></tr><tr><td>36</td><td>ไทยพร้อม</td><td>0 (ศูนย์)</td></tr><tr><td>37</td><td>ภูมิใจไทย</td><td>39 (สามสิบเก้า)</td></tr><tr><td>38</td><td>พลังธรรมใหม่</td><td>1 (หนึ่ง)</td></tr><tr><td>39</td><td>กรีน</td><td>1 (หนึ่ง)</td></tr><tr><td>40</td><td>ไทยธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>41</td><td>แผ่นดินธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>42</td><td>กล้าธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>43</td><td>พลังประชารัฐ</td><td>0 (ศูนย์)</td></tr><tr><td>44</td><td>โอกาสใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>45</td><td>เป็นธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>46</td><td>ประชาชน</td><td>25 (สี่สิบห้า)</td></tr><tr><td>47</td><td>ประชาไทย</td><td>0 (ศูนย์)</td></tr><tr><td>48</td><td>ไทยสร้างไทย</td><td>0 (ศูนย์)</td></tr><tr><td>49</td><td>ไทยก้าวใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>50</td><td>ประชาอาสาชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>51</td><td>พร้อม</td><td>0 (ศูนย์)</td></tr><tr><td>52</td><td>เครือข่ายชาวนาแห่งประเทศไทย</td><td>0 (ศูนย์)</td></tr><tr><td>53</td><td>ไทยพิทักษ์ธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>54</td><td>ความหวังใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>55</td><td>ไทยรวมไทย</td><td>0 (ศูนย์)</td></tr><tr><td>56</td><td>เพื่อบ้านเมือง</td><td>0 (ศูนย์)</td></tr><tr><td>57</td><td>พลังไทยรักชาติ</td><td>0 (ศูนย์)</td></tr><tr><td colspan="2">รวมคะแนนทั้งสิ้น</td><td>156 (หนึ่งร้อยห้าสิบหก)</td></tr></table>

สำเนาถูกต้อง
นายทะเบียนเลือกตั้งประจำจังหวัดสมุทรปราการ

[Page 4] party scores read: 23 entries


meta: {'eligible': 210, 'show_up': 163, 'prepared_cards': 200, 'used_cards': 163, 'good_cards': 156, 'bad_cards': 7, 'no_vote_cards': 0, 'remaining_cards': 37}
total score: 150 | COMPLETE

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่15/15.pdf
============================================================
 Total pages: 6
[Page 0] SKIPPED (constituency pipeline)
[Page 1] SKIPPED
[Page 2] Done
[Page 3] Done
[Page 4] Done
[Page 5] SKIPPED


============================================================

Raw content from page 2:

ส.ส. ๕/๑๘ (บช)
สีขาว

# ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบบัญชีรายชื่อ)

รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อ

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2567 เป็นวันเลือกตั้ง นั้น

บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบบัญชีรายชื่อของหน่วยเลือกตั้งที่ 1/5 หมู่ที่ 1/5 ตำบล/แขวง/เทศบาล อำเภอ/เขต อำเภอ/เขต จังหวัด นครราชสีมา เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของหน่วยเลือกตั้งดังกล่าว ดังนี้

## ๑. จำนวนผู้มีสิทธิเลือกตั้ง


### Debug: Row Entries

In [ ]:
df_debug = pd.DataFrame(debug_rows)
df_debug = df_debug.sort_values(["sub-district", "unit"]).reset_index(drop=True)
df_debug

,sub-district,unit,page 2 entries,page 3 entries,page 4 entries,total entries
0,ทุ่งสว่าง,1,10,24,23,57
1,ทุ่งสว่าง,2,10,24,23,57
2,ทุ่งสว่าง,3,10,24,23,57
3,ทุ่งสว่าง,4,10,24,23,57
4,ทุ่งสว่าง,5,10,0,23,33
...,...,...,...,...,...,...
67,เทศบาลตำบลบุสูง,18,10,24,23,57
68,เทศบาลตำบลบุสูง,19,10,24,23,57
69,เทศบาลตำบลบุสูง,20,10,24,23,57
70,เทศบาลตำบลบุสูง,21,10,24,23,57
71,เทศบาลตำบลบุสูง,22,10,24,23,57

In [ ]:
df_debug.to_csv("(debug)party_list_entries.csv", index=False, encoding="utf-8-sig")
print("Saved: (debug)party_list_entries.csv")

Saved: (debug)party_list_entries.csv

In [ ]:
from google.colab import files
files.download("(debug)party_list_entries.csv")

## party_list.csv (grouped by units and by sub-district)

columns: `sub_district`, `party1`, `party2`, ..., `party57`

In [ ]:
df_units = pd.DataFrame(party_unit_rows) ## อันนี้แยกตามหน่วย น่าจะ validate ง่ายกว่า
print("=== party_list (grouped by ) ===")

df_units = df_units.sort_values(
    by=["ตำบล", "หน่วยเลือกตั้ง"],
    ascending=[True, True]
).reset_index(drop=True)

print(f"Rows: {len(df_units)}")

=== party_list (grouped by ) ===
Rows: 72

In [ ]:
df_units

,source_pdf,ตำบล,หน่วยเลือกตั้ง,pages_read,eligible,show_up,prepared_cards,used_cards,good_cards,bad_cards,...,ไทยสร้างไทย,ไทยก้าวใหม่,ประชาอาสาชาติ,พร้อม,เครือข่ายชาวนาแห่งประเทศไทย,ไทยพิทักษ์ธรรม,ความหวังใหม่,ไทยรวมไทย,เพื่อบ้านเมือง,พลังไทยรักชาติ
0,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่1/1.pdf,ทุ่งสว่าง,1,3,219,NaN,220,150,NaN,NaN,...,1,1,0,1,0,0,0,0,0,0
1,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่2/2.pdf,ทุ่งสว่าง,2,3,310,178.0,300,178,170.0,8.0,...,0,0,0,0,0,0,0,0,0,0
2,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่3/3.pdf,ทุ่งสว่าง,3,3,205,125.0,200,125,124.0,0.0,...,1,0,0,0,0,0,0,0,0,0
3,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่4/4.pdf,ทุ่งสว่าง,4,3,158,106.0,160,106,104.0,2.0,...,2,0,0,0,0,0,0,0,0,0
4,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่5/5.pdf,ทุ่งสว่าง,5,3,318,200.0,320,200,NaN,188.0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่18/18.pdf,เทศบาลตำบลบุสูง,18,3,171,NaN,180,128,115.0,8.0,...,0,0,0,0,0,0,0,0,0,0
68,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่19/19.pdf,เทศบาลตำบลบุสูง,19,3,305,NaN,300,206,NaN,NaN,...,0,0,1,0,0,0,0,0,0,1
69,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่20/20.pdf,เทศบาลตำบลบุสูง,20,3,167,80.0,163,80,75.0,5.0,...,0,0,1,0,0,0,0,0,0,0
70,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่21/21.pdf,เทศบาลตำบลบุสูง,21,3,148,91.0,160,91,55.0,5.0,...,0,0,0,0,0,0,0,0,0,0
71,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่22/22.pdf,เทศบาลตำบลบุสูง,22,3,386,NaN,380,219,208.0,8.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_units[["ประชาชน", "ภูมิใจไทย"]]

    ประชาชน  ภูมิใจไทย
0        32         26
1        80         38
2        17         68
3         9         35
4        36         57
..      ...        ...
67       12         27
68       17         68
69        0         30
70       16         34
71       39         42

[72 rows x 2 columns]

In [ ]:
df_units["ภูมิใจไทย"].sum()

np.int64(23522)

In [ ]:
df_units[["used_cards","good_cards","bad_cards","no_vote_cards"]]

    used_cards  good_cards  bad_cards  no_vote_cards
0          150         NaN        NaN            3.0
1          178       170.0        8.0            NaN
2          125       124.0        0.0            1.0
3          106       104.0        2.0            NaN
4          200         NaN      188.0            2.0
..         ...         ...        ...            ...
67         128       115.0        8.0            5.0
68         206         NaN        NaN          146.0
69          80        75.0        5.0            0.0
70          91        55.0        5.0            1.0
71         219       208.0        8.0            3.0

[72 rows x 4 columns]

In [ ]:
subdistrict_col = "ตำบล"

cols_to_sum = ["used_cards","good_cards","bad_cards","no_vote_cards"] + PARTY_NAMES

df_agg = (
    df_units
    .groupby(subdistrict_col, dropna=False)[cols_to_sum]
    .sum()
    .reset_index()
    .rename(columns={subdistrict_col: "sub_district"})
)

print("=== party_list (grouped by sub-district) ===") # อันนี้ คือ แยกตามตำบลนะ
print(f"Rows: {len(df_agg)}")

df_agg

=== party_list (grouped by sub-district) ===
Rows: 4

,sub_district,used_cards,good_cards,bad_cards,no_vote_cards,ไทยทรัพย์ทวี,เพื่อชาติไทย,ใหม่,มิติใหม่,รวมใจไทย,...,ไทยสร้างไทย,ไทยก้าวใหม่,ประชาอาสาชาติ,พร้อม,เครือข่ายชาวนาแห่งประเทศไทย,ไทยพิทักษ์ธรรม,ความหวังใหม่,ไทยรวมไทย,เพื่อบ้านเมือง,พลังไทยรักชาติ
0,ทุ่งสว่าง,2239,1686.0,264.0,20.0,117,43,36,10,46,...,7,3,1,2,0,1,1,0,0,4
1,ธาตุ,3654,3040.0,356.0,16.0,275,54,61,6,636,...,19,5,5,3,4,4,4,4,4,10
2,บ่อแก้ว,3134,2668.0,391.0,23.0,89,372,269,118,172,...,6,6,3,4,8,3,3,5,4,248
3,เทศบาลตำบลบุสูง,4992,4385.0,228.0,219.0,18,56,260,9,121,...,16,1,2,0,6,0,2,1,2,4

## Export & Download

In [ ]:
df_agg.to_csv("party_list.csv", index=False, encoding="utf-8-sig")
df_units.to_csv("party_list_by_unit.csv", index=False, encoding="utf-8-sig")

print("Saved: party_list.csv (ระดับตำบล)")
print("Saved: party_list_by_unit.csv (ระดับหน่วย)")

Saved: party_list.csv (ระดับตำบล)
Saved: party_list_by_unit.csv (ระดับหน่วย)

In [ ]:
from google.colab import files
files.download("party_list.csv")
files.download("party_list_by_unit.csv")

# Pipeline: Constituency

## Pre-DataFrame: 9 Candidates

In [ ]:
CONSTITUENCY_CANDIDATES = {
    1: "นายสุเกษม เรืองนุช",
    2: "นายเนียม ผลบุญ",
    3: "นายธเนส เครือรัตน์",
    4: "นายวีรชัย จันทร์ดวงศรี",
    5: "นายสิริพงศ์ อังคสกุลเกียรติ",
    6: "นายสุรเดช นาจำปา",
    7: "นายคณีศร คำโสภา",
    8: "นายกุลธวัช สาลี",
    9: "นางสาวฉวี ปิ่นทอม",
}

CAND_COLS = {num: f"ชื่อนามสกุลผู้สมัครหมายเลข{num}" for num in range(1, 10)}

print(f"Constituency candidates pre-loaded: {len(CONSTITUENCY_CANDIDATES)} คน")
for num, name in CONSTITUENCY_CANDIDATES.items():
    print(f"  {num}. {name}")

Constituency candidates pre-loaded: 9 คน
  1. นายสุเกษม เรืองนุช
  2. นายเนียม ผลบุญ
  3. นายธเนส เครือรัตน์
  4. นายวีรชัย จันทร์ดวงศรี
  5. นายสิริพงศ์ อังคสกุลเกียรติ
  6. นายสุรเดช นาจำปา
  7. นายคณีศร คำโสภา
  8. นายกุลธวัช สาลี
  9. นางสาวฉวี ปิ่นทอม

## Helper Functions: Constituency

In [ ]:
def extract_constituency_scores_page0(ocr_text):
    soup = BeautifulSoup(ocr_text, "html.parser")
    scores = {}
    for table in soup.find_all("table"):
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if len(cols) < 2:
                continue
            if is_summary_row(cols):
                continue
            num_str = cols[0].translate(str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")).strip()
            if not re.match(r"^\d+$", num_str):
                continue
            cand_num = int(num_str)
            if cand_num < 1 or cand_num > 9:
                continue
            score = clean_score(cols[-1])
            scores[cand_num] = score if score is not None else 0
    return scores

def extract_meta_constituency(ocr_text):
    return extract_meta(ocr_text)

## Pipeline: OCR

In [ ]:
con_unit_rows  = []   # df_units_constituency
con_debug_rows = []   # debug_df_constituency

for subdistrict_name, pdf_paths_sd in subdistrict_pdf_map.items():
    print("\n" + "#"*60)
    print(f" ตำบล: {subdistrict_name}  ({len(pdf_paths_sd)} หน่วย)")
    print("#"*60)

    for pdf_path in pdf_paths_sd:
        pdf_filename = os.path.basename(pdf_path)
        print("\n" + "="*60)
        print(f" PDF: {pdf_path}")
        print("="*60)

        pages = convert_from_path(pdf_path, 300)
        print(f" Total pages: {len(pages)}")

        # อ่านแค่ page[0]
        img_path = "con_page_0.jpg"
        pages[0].save(img_path, "JPEG")

        try:
            ocr_text = typhoon_ocr.ocr_document(img_path)
            print("[Page 0] Done")
        except Exception as e:
            print(f"[Page 0] Error: {e}")
            ocr_text = ""

        # debug: raw output
        print("="*60)
        print("\nRaw content from page 0:\n")
        print(ocr_text)
        print("="*60)

        meta   = extract_meta_constituency(ocr_text)
        scores = extract_constituency_scores_page0(ocr_text)

        print(f"\n[Page 0] constituency scores read: {len(scores)} entries")
        print(f"scores: {scores}")

        try:
            unit_num = int(pdf_filename.split('.')[0])
        except ValueError:
            unit_num = pdf_filename

        row = {
            "source_pdf"          : pdf_path,
            "ตำบลหน่วยเลือกตั้ง" : subdistrict_name,
            "eligible"            : meta.get("eligible"),
            "show_up"             : meta.get("show_up"),
            "prepared_cards"      : meta.get("prepared_cards"),
            "used_cards"          : meta.get("used_cards"),
            "good_cards"          : meta.get("good_cards"),
            "bad_cards"           : meta.get("bad_cards"),
        }
        for num, col_name in CAND_COLS.items():
            row[col_name] = scores.get(num, 0)

        con_unit_rows.append(row)

        # debug row
        con_debug_rows.append({
            "sub-district"  : subdistrict_name,
            "unit"          : unit_num,
            "page 0 entries": len(scores),
            "completeness"    : "yes" if len(scores) == 9 else f"{len(scores)}/9",
        })

print("\n" + "="*60)
print(f" TOTAL units processed: {len(con_unit_rows)}")

############################################################
 ตำบล: ทุ่งสว่าง  (15 หน่วย)
############################################################

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่1/1.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบแบ่งเขตเลือกตั้ง)

รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขตเลือกตั้ง

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 28 เดือน กุมภาพันธ์ พ.ศ. 2567 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขต เลือกตั้งของหน่วยเลือกตั้งที่ 1 หมู่ที่ 1 ตำบล/แขวง/เทศบาล กะท่าง อำเภอ/เขต วังนิ่ม เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของ หน่วยเลือกตั้งดังกล่าว ดังนี้
๑. จำนวนผู้มีสิทธิเลือกตั้ง
    ๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 219 คน (สองร้อยสิบเก้า)
    ๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 150 คน (หนึ่งร้อยห้าสิบ)
๒. จำนวนบัตรเลือกตั้ง
    ๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 220 บัตร (สองร้อยยี่สิบ)
    ๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 150 บัตร (หนึ่งร้อยห้าสิบ)
    ๒.๒.๑ บัตรดี จำนวน 147 บัตร (หนึ่งร้อยสี่สิบเจ็ด)
    ๒.๒.๒ บัตรเสีย จำนวน 2 บัตร (สอง)
    ๒.๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด จำนวน 1 บัตร (หนึ่ง)
    ๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 70 บัตร (เจ็ดสิบ)
๓. จำนวนคะแนนที่ผู้สมัครรับเลือกตั้งแต่ละคนได้รับเรียงตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลขประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>พรรคการเมือง</td><td>สังกัด</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>นายสุขเกษม เรืองนุช</td><td>ประชาชน</td><td>14</td><td>( สิบสี่ )</td></tr><tr><td>2</td><td>นายเนียม ผลบุญ</td><td>ประชาธิปไตยใหม่</td><td>6</td><td>( หก )</td></tr><tr><td>3</td><td>นายธเนศ เครือรัตน์</td><td>เพื่อไทย</td><td>42</td><td>( สี่สิบสอง )</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ประชาธิปัตย์</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td>5</td><td>นายสิริพงศ์ อังคสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>89</td><td>( แป้ง )</td></tr><tr><td>6</td><td>นายสุรเดช นาจำปา</td><td>กล้าธรรม</td><td>1</td><td>( หนึ่ง )</td></tr><tr><td>7</td><td>นายคณิศร คำโสภา</td><td>เศรษฐกิจ</td><td>1</td><td>( หนึ่ง )</td></tr><tr><td>8</td><td>นายกุลธวัช สาลี</td><td>รวมไทยสร้างชาติ</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td>9</td><td>นางสาวฉวี ปิ่นหอม</td><td>ปวงชนไทย</td><td>0</td><td>( ศูนย์ )</td></tr><tr><td colspan="4">รวมคะแนนทั้งสิ้น</td><td>150 47 ( หนึ่งร้อยห้าสิบเจ็ด หนึ่งร้อยสี่สิบหก )</td></tr></table>

(ลายเซ็น)
============================================================

[Page 0] constituency scores read: 9 entries
scores: {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่10/10.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบแบ่งเขตเลือกตั้ง)

รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขตเลือกตั้ง

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขต เลือกตั้งของหน่วยเลือกตั้งที่ 10 หมู่ที่ 10 ตำบล/แขวง/เทศบาล ทุ่งสังข์ อำเภอ/เขต วังเหนือ
เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของ หน่วยเลือกตั้งดังกล่าว ดังนี้
๑. จำนวนผู้มีสิทธิเลือกตั้ง
    ๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 236 คน ( หัวใจของแผ่นป้าย )
    ๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 129 คน ( หัวใจของผู้รับเลือกตั้ง )
๒. จำนวนบัตรเลือกตั้ง
    ๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 240 บัตร ( หัวใจของผู้รับเลือกตั้ง )
    ๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 129 บัตร ( หัวใจของผู้รับเลือกตั้ง )
    ๒.๒.๑ บัตรดี จำนวน 124 บัตร ( หัวใจของผู้รับเลือกตั้ง )
    ๒.๒.๒ บัตรเสีย จำนวน 5 บัตร ( หัวใจของผู้รับเลือกตั้ง )
    ๒.๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด จำนวน - บัตร ( หัวใจของผู้รับเลือกตั้ง )
    ๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 111 บัตร ( หัวใจของผู้รับเลือกตั้ง )
๓. จำนวนคะแนนที่ผู้สมัครรับเลือกตั้งแต่ละคนได้รับเรียงตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลขประจำตัว<br/>ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล<br/>ผู้สมัครรับเลือกตั้ง</td><td>สังกัด<br/>พรรคการเมือง</td><td>ได้คะแนน<br/>(ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>นายสุขเกษม เรืองนุช</td><td>ประชาชน</td><td>10 ( สิง )</td></tr><tr><td>2</td><td>นายเนียม ผลบุญ</td><td>ประชาธิปไตยใหม่</td><td>2 ( สอง )</td></tr><tr><td>3</td><td>นายธเนศ เครือรัตน์</td><td>เพื่อไทย</td><td>44 ( สี่สิบสี่ )</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ประชาธิปัตย์</td><td>0 ( ศูนย์ )</td></tr><tr><td>5</td><td>นายสิริพงศ์ อังคสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>64 ( หกสิบสี่ )</td></tr><tr><td>6</td><td>นายสุรเดช นาจำปา</td><td>กล้าธรรม</td><td>0 ( ศูนย์ )</td></tr><tr><td>7</td><td>นายคณิศร คำโสภา</td><td>เศรษฐกิจ</td><td>23 ( สาม )</td></tr><tr><td>8</td><td>นายกุลธวัช สาลี</td><td>รวมไทยสร้างชาติ</td><td>0 ( ศูนย์ )</td></tr><tr><td>9</td><td>นางสาวฉวี ปิ่นหอม</td><td>ปวงชนไทย</td><td>591 ( หนึ่งร้อยเก้าสิบเอ็ด )</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>0124 ( หนึ่งร้อยสี่สิบสี่ )</td></tr></table>
============================================================

[Page 0] constituency scores read: 9 entries
scores: {1: 10, 2: 2, 3: 44, 4: 0, 5: 64, 6: 0, 7: 23, 8: 0, 9: 591}

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่11/11.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบแบ่งเขตเลือกตั้ง)
รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขตเลือกตั้ง

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขต เลือกตั้งของหน่วยเลือกตั้งที่ 11 หมู่ที่ 11 ตำบล/แขวง/เทศบาล หนองหอย อำเภอ/เขต อวิทิน
เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของ หน่วยเลือกตั้งดังกล่าว ดังนี้

๑. จำนวนผู้มีสิทธิเลือกตั้ง
    ๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 240 คน ( ลงชื่อ พร้อมลายเซ็น )
    ๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 171 คน ( ลงชื่อ พร้อมลายเซ็น )

๒. จำนวนบัตรเลือกตั้ง
    ๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 240 บัตร ( ลงชื่อ พร้อมลายเซ็น )
    ๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 171 บัตร ( ลงชื่อ พร้อมลายเซ็น )
    ๒.๒.๑ บัตรดี จำนวน 177 บัตร ( ลงชื่อ พร้อมลายเซ็น )
    ๒.๒.๒ บัตรเสีย จำนวน 4 บัตร ( ลงชื่อ พร้อมลายเซ็น )
    ๒.๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด จำนวน 0 บัตร ( ลงชื่อ พร้อมลายเซ็น )
    ๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 69 บัตร ( ลงชื่อ พร้อมลายเซ็น )

๓. จำนวนคะแนนที่ผู้สมัครรับเลือกตั้งแต่ละคนได้รับเรียงตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลขประจำตัว<br/>ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล<br/>ผู้สมัครรับเลือกตั้ง</td><td>สังกัด<br/>พรรคการเมือง</td><td>ได้คะแนน<br/>(ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>นายสุขเกษม เรืองนุช</td><td>ประชาชน</td><td>13 ( สิงถาม )</td></tr><tr><td>2</td><td>นายเนียม ผลบุญ</td><td>ประชาธิปไตยใหม่</td><td>1 ( หนึ่ง )</td></tr><tr><td>3</td><td>นายธเนศ เครือรัตน์</td><td>เพื่อไทย</td><td>71 ( หลักสิบเอ็ด )</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ประชาธิปัตย์</td><td>0 ( ศูนย์ )</td></tr><tr><td>5</td><td>นายสิริพงศ์ อังคสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>80 ( แปดสิบ )</td></tr><tr><td>6</td><td>นายสุรเดช นาจำปา</td><td>กล้าธรรม</td><td>0 ( ศูนย์ )</td></tr><tr><td>7</td><td>นายคณิศร คำโสภา</td><td>เศรษฐกิจ</td><td>1 ( หนึ่ง )</td></tr><tr><td>8</td><td>นายกุลธวัช สาลี</td><td>รวมไทยสร้างชาติ</td><td>1 ( หนึ่ง )</td></tr><tr><td>9</td><td>นางสาวฉวี ปิ่นหอม</td><td>ปวงชนไทย</td><td>0 ( ศูนย์ )</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>117 ( หนึ่งร้อยหกสิบเจ็ด )</td></tr></table>
============================================================

[Page 0] constituency scores read: 9 entries
scores: {1: 13, 2: 1, 3: 71, 4: 0, 5: 80, 6: 0, 7: 1, 8: 1, 9: 0}

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่12/12.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว

รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขตเลือกตั้ง

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขต เลือกตั้งของหน่วยเลือกตั้งที่ 12 หมู่ที่ 12 ตำบล/แขวง/เทศบาล อำเภอ/เขต วัดหิน
เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของ หน่วยเลือกตั้งดังกล่าว ดังนี้

๑. จำนวนผู้มีสิทธิเลือกตั้ง
    ๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 173 คน (หนึ่งร้อยเจ็ดสิบสาม)
    ๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 104 คน (หนึ่งร้อยสี่)

๒. จำนวนบัตรเลือกตั้ง
    ๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 180 บัตร (หนึ่งร้อยแปดสิบ)
    ๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 104 บัตร (หนึ่งร้อยสี่)
    ๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด จำนวน 4 บัตร (  )
    ๒.๔ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 0 บัตร ( เขตส่วนนอก )

๓. จำนวนคะแนนที่ผู้สมัครรับเลือกตั้งแต่ละคนได้รับเรียงตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลขประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัด พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกช่องตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>นายสุขเกษม เรืองบุช</td><td>ประชาชน</td><td>4 ( ส )</td></tr><tr><td>2</td><td>นายเนียม ผลบุญ</td><td>ประชาธิปไตยใหม่</td><td>0 ( ศ )</td></tr><tr><td>3</td><td>นายธเนศ เครือรัตน์</td><td>เพื่อไทย</td><td>54 ( หัวส้ม )</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ประชาธิปัตย์</td><td>0 ( ศ )</td></tr><tr><td>5</td><td>นายสิริพงศ์ อังคสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>41 ( สส )</td></tr><tr><td>6</td><td>นายสุรเดช นาจำปา</td><td>กล้าธรรม</td><td>0 ( ศ )</td></tr><tr><td>-7</td><td>นายคณิศร คำโสภา</td><td>เศรษฐกิจ</td><td>1 ( ศ )</td></tr><tr><td>8</td><td>นายกุลธวัช สาลี</td><td>รวมไทยสร้างชาติ</td><td>0 ( ศ )</td></tr><tr><td>9</td><td>นางสาวฉวี ปิ่นหอม</td><td>ปวงชนไทย</td><td>0 ( ศ )</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>100 ( หนึ่งร้อย )</td></tr></table>
============================================================

[Page 0] constituency scores read: 8 entries
scores: {1: 4, 2: 0, 3: 54, 4: 0, 5: 41, 6: 0, 8: 0, 9: 0}

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่13/13.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว

ชุดที่ ๑ เก็บไว้ในเล่มเพื่อส่งคณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง (แบบแบ่งเขตเลือกตั้ง)

รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขตเลือกตั้ง

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2567 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขต เลือกตั้งของหน่วยเลือกตั้งที่ 13 หมู่ที่ 13 ตำบล/แขวง/เทศบาล ทุ่งสร้าง อำเภอ/เขต จังหวัด
เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของ หน่วยเลือกตั้งดังกล่าว ดังนี้

๑. จำนวนผู้มีสิทธิเลือกตั้ง
๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 222 คน (สองร้อยยี่สิบสอง)
๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 125 คน (หนึ่งร้อยยี่สิบห้า)

๒. จำนวนบัตรเลือกตั้ง
๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 220 บัตร (สองร้อยยี่สิบบัตร)
๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 125 บัตร (หนึ่งร้อยยี่สิบห้าบัตร)
๒.๒.๑ บัตรดี จำนวน 120 บัตร (หนึ่งร้อยยี่สิบบัตร)
๒.๒.๒ บัตรเสีย จำนวน 4 บัตร (สี่)
๒.๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด จำนวน 1 บัตร (หนึ่ง)
๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 95 บัตร (เก้าสิบห้า)

๓. จำนวนคะแนนที่ผู้สมัครรับเลือกตั้งแต่ละคนได้รับเรียงตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลขประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัด พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>นายสุขเกษม เรืองนุช</td><td>ประชาชน</td><td>5 (ห้า)</td></tr><tr><td>2</td><td>นายเนียม ผลบุญ</td><td>ประชาธิปไตยใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>3</td><td>นายธเนศ เครือรัตน์</td><td>เพื่อไทย</td><td>28 (ยี่สิบแปด)</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ประชาธิปัตย์</td><td>1 (หนึ่ง)</td></tr><tr><td>5</td><td>นายสิริพงศ์ อังคสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>35 (แปดสิบห้า)</td></tr><tr><td>6</td><td>นายสุรเดช นาจำปา</td><td>กล้าธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>7</td><td>นายคณิศร คำโสภา</td><td>เศรษฐกิจ</td><td>0 (ศูนย์)</td></tr><tr><td>8</td><td>นายกุลธวัช สาลี</td><td>รวมไทยสร้างชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>9</td><td>นางสาวฉวี ปิ่นหอม</td><td>ปวงชนไทย</td><td>1 (หนึ่ง)</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>0 (ศูนย์)</td></tr></table>
============================================================

[Page 0] constituency scores read: 9 entries
scores: {1: 5, 2: 0, 3: 28, 4: 1, 5: 35, 6: 0, 7: 0, 8: 0, 9: 1}

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่14/14.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว

รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขตเลือกตั้ง

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2567 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขต เลือกตั้งของหน่วยเลือกตั้งที่ 14 หมู่ที่ 14 ตำบล/แขวง/เทศบาล ถลาง อำเภอ/เขต ถลาง
เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของ หน่วยเลือกตั้งดังกล่าว ดังนี้
๑. จำนวนผู้มีสิทธิเลือกตั้ง
๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 210 คน (สองร้อยสิบ)
๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 163 คน (หนึ่งร้อยหกสิบสาม)
๒. จำนวนบัตรเลือกตั้ง
๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 200 บัตร (สองร้อย)
๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 163 บัตร (หนึ่งร้อยหกสิบสาม)
๒.๒.๑ บัตรดี จำนวน 156 บัตร (หนึ่งร้อยหกสิบสาม)
๒.๒.๒ บัตรเสีย จำนวน 37 บัตร (สามสิบเจ็ด)
๒.๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด จำนวน - บัตร (-)
๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 37 บัตร (สามสิบเจ็ด)

๓. จำนวนคะแนนที่ผู้สมัครรับเลือกตั้งแต่ละคนได้รับเรียงตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลขประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัด พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>นายสุขเกษม เรืองนุช</td><td>ประชาชน</td><td>12 (สิบสอง)</td></tr><tr><td>2</td><td>นายเนียม ผลบุญ</td><td>ประชาธิปไตยใหม่</td><td>2 (สอง)</td></tr><tr><td>3</td><td>นายธเนศ เครือรัตน์</td><td>เพื่อไทย</td><td>61 (หกสิบเอ็ด)</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ประชาธิปัตย์</td><td>0 (ศูนย์)</td></tr><tr><td>5</td><td>นายสิริพงศ์ อังคสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>84 (แปดสิบสี่)</td></tr><tr><td>6</td><td>นายสุรเดช นาจำปา</td><td>กล้าธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>7</td><td>นายคณิศร คำโสภา</td><td>เศรษฐกิจ</td><td>0 (ศูนย์)</td></tr><tr><td>8</td><td>นายกุลธวัช สาลี</td><td>รวมไทยสร้างชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>9</td><td>นางสาวฉวี ปิ่นหอม</td><td>ปวงชนไทย</td><td>1 (หนึ่ง)</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>160 (หนึ่งร้อยหกสิบ)</td></tr></table>
============================================================

[Page 0] constituency scores read: 9 entries
scores: {1: 12, 2: 2, 3: 61, 4: 0, 5: 84, 6: 0, 7: 0, 8: 0, 9: 1}

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่15/15.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว

# รายงานผลการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขตเลือกตั้ง

ตามที่ได้มีพระราชกฤษฎีกาให้มีการเลือกตั้งสมาชิกสภาผู้แทนราษฎร และคณะกรรมการการเลือกตั้ง ได้กำหนดให้วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569 เป็นวันเลือกตั้ง นั้น
บัดนี้ คณะกรรมการประจำหน่วยเลือกตั้งได้ดำเนินการนับคะแนนสมาชิกสภาผู้แทนราษฎรแบบแบ่งเขต เลือกตั้งของหน่วยเลือกตั้งที่ 15 หมู่ที่ 15 ตำบล/แขวง/เทศบาล สุขสวัสดิ์ อำเภอ/เขต คันหิน
เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ เสร็จสิ้นเป็นที่เรียบร้อยแล้ว ดังนั้น จึงขอรายงานผลการนับคะแนนของ หน่วยเลือกตั้งดังกล่าว ดังนี้
๑. จำนวนผู้มีสิทธิเลือกตั้ง
๑.๑ จำนวนผู้มีสิทธิเลือกตั้งตามบัญชีรายชื่อผู้มีสิทธิเลือกตั้ง จำนวน 295 คน (สองร้อยเก้าสิบห้า)
๑.๒ จำนวนผู้มีสิทธิเลือกตั้งที่มาแสดงตน (เฉพาะวันเลือกตั้ง) จำนวน 270 คน (หนึ่งร้อยเจ็ดสิบ)
๒. จำนวนบัตรเลือกตั้ง
๒.๑ จำนวนบัตรเลือกตั้งที่ได้รับจัดสรร จำนวน 300 บัตร (สามร้อยบัตร)
๒.๒ จำนวนบัตรเลือกตั้งที่ใช้ จำนวน 175 บัตร (หนึ่งร้อยห้า)
๒.๒.๑ บัตรดี จำนวน 169 บัตร (หนึ่งร้อยเก้าสิบเก้า)
๒.๒.๒ บัตรเสีย จำนวน 12 บัตร (สอง)
๒.๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด จำนวน 1 บัตร (หนึ่ง)
๒.๓ จำนวนบัตรเลือกตั้งที่เหลือ จำนวน 225 บัตร (หนึ่งร้อยยี่สิบห้า)

๓. จำนวนคะแนนที่ผู้สมัครรับเลือกตั้งแต่ละคนได้รับเรียงตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลขประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัด พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>1</td><td>นายสุขเกษม เรืองนุช</td><td>ประชาชน</td><td>8 (แปด)</td></tr><tr><td>2</td><td>นายเนียม ผลบุญ</td><td>ประชาธิปไตยใหม่</td><td>1 (เอ็ด)</td></tr><tr><td>3</td><td>นายธเนศ เครือรัตน์</td><td>เพื่อไทย</td><td>92 (เก้าสิบสอง)</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ประชาธิปัตย์</td><td>9 (เก้า)</td></tr><tr><td>5</td><td>นายสิริพงศ์ อังคสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>86 (แปดสิบหก)</td></tr><tr><td>6</td><td>นายสุรเดช นาจำปา</td><td>กล้าธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>7</td><td>นายคณิศร คำโสภา</td><td>เศรษฐกิจ</td><td>2 (สอง)</td></tr><tr><td>8</td><td>นายกุลธวัช สาลี</td><td>รวมไทยสร้างชาติ</td><td>0 (ศูนย์)</td></tr><tr><td>9</td><td>นางสาวฉวี ปิ่นหอม</td><td>ปวงชนไทย</td><td>3 (สาม)</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>172 (หนึ่งร้อยเจ็ดสิบสอง)</td></tr></table>
============================================================

[Page 0] constituency scores read: 9 entries
scores: {1: 8, 2: 1, 3: 92, 4: 9, 5: 86, 6: 0, 7: 2, 8: 0, 9: 3}

============================================================
 PDF: data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่2/2.pdf
============================================================
 Total pages: 6
[Page 0] Done
============================================================

Raw content from page 0:

ส.ส. ๕/๑๘
สีขาว


## Export Dataframe

In [ ]:
df_units_constituency = pd.DataFrame(con_unit_rows)

rename_map = {f"ชื่อนามสกุลผู้สมัครหมายเลข{num}": CONSTITUENCY_CANDIDATES[num]
              for num in range(1, 10)}
df_units_display = df_units_constituency.rename(columns=rename_map)

print("\n=== df_units_constituency ===")
print(f"Rows: {len(df_units_constituency)}")
display(df_units_display)

=== df_units_constituency ===
Rows: 72

,source_pdf,ตำบลหน่วยเลือกตั้ง,eligible,show_up,prepared_cards,used_cards,good_cards,bad_cards,นายสุเกษม เรืองนุช,นายเนียม ผลบุญ,นายธเนส เครือรัตน์,นายวีรชัย จันทร์ดวงศรี,นายสิริพงศ์ อังคสกุลเกียรติ,นายสุรเดช นาจำปา,นายคณีศร คำโสภา,นายกุลธวัช สาลี,นางสาวฉวี ปิ่นทอม
0,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่1/1.pdf,ทุ่งสว่าง,219,150.0,220,150,147.0,2.0,0,0,0,0,0,0,0,0,0
1,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่10/10.pdf,ทุ่งสว่าง,236,129.0,240,129,124.0,5.0,10,2,44,0,64,0,23,0,591
2,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่11/11.pdf,ทุ่งสว่าง,240,171.0,240,171,177.0,4.0,13,1,71,0,80,0,1,1,0
3,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่12/12.pdf,ทุ่งสว่าง,173,104.0,180,104,NaN,NaN,4,0,54,0,41,0,0,0,0
4,data/1.ทุ่งสว่าง/หน่วยเลือกตั้งที่13/13.pdf,ทุ่งสว่าง,222,125.0,220,125,120.0,4.0,5,0,28,1,35,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่5/5.pdf,เทศบาลตำบลบุสูง,710,427.0,680,427,NaN,16.0,39,3,137,0,218,2,0,0,11
68,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่6/6.pdf,เทศบาลตำบลบุสูง,373,195.0,360,195,190.0,3.0,12,0,89,1,84,0,2,0,2
69,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่7/7.pdf,เทศบาลตำบลบุสูง,361,296.0,360,296,228.0,6.0,12,0,100,0,110,1,0,0,5
70,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่8/8.pdf,เทศบาลตำบลบุสูง,666,357.0,640,357,350.0,6.0,11,1,134,2,193,0,0,0,9
71,data/4.เทศบาลตำบลบุสูง/หน่วยเลือกตั้งที่9/9.pdf,เทศบาลตำบลบุสูง,268,180.0,260,130,167.0,10.0,7,0,48,2,87,2,0,0,23

In [ ]:
debug_df_constituency = pd.DataFrame(con_debug_rows)
print("\n=== debug_df_constituency ===")
display(debug_df_constituency)

=== debug_df_constituency ===

       sub-district  unit  page 0 entries completeness
0         ทุ่งสว่าง     1               9          yes
1         ทุ่งสว่าง    10               9          yes
2         ทุ่งสว่าง    11               9          yes
3         ทุ่งสว่าง    12               8          8/9
4         ทุ่งสว่าง    13               9          yes
..              ...   ...             ...          ...
67  เทศบาลตำบลบุสูง     5               9          yes
68  เทศบาลตำบลบุสูง     6               9          yes
69  เทศบาลตำบลบุสูง     7               9          yes
70  เทศบาลตำบลบุสูง     8               9          yes
71  เทศบาลตำบลบุสูง     9               9          yes

[72 rows x 4 columns]

In [ ]:
score_cols = list(CAND_COLS.values())

agg_dict = {"source_pdf": "count"}
agg_dict.update({col: "sum" for col in score_cols})

df_agg_constituency = (
    df_units_constituency
    .groupby("ตำบลหน่วยเลือกตั้ง", as_index=False)
    .agg(agg_dict)
    .rename(columns={"source_pdf": "จำนวนหน่วย"})
)

df_agg_constituency = df_agg_constituency.rename(columns=rename_map)

print("\n=== df_agg_constituency ===")
print(f"Rows: {len(df_agg_constituency)}")
display(df_agg_constituency)

=== df_agg_constituency ===
Rows: 4

,ตำบลหน่วยเลือกตั้ง,จำนวนหน่วย,นายสุเกษม เรืองนุช,นายเนียม ผลบุญ,นายธเนส เครือรัตน์,นายวีรชัย จันทร์ดวงศรี,นายสิริพงศ์ อังคสกุลเกียรติ,นายสุรเดช นาจำปา,นายคณีศร คำโสภา,นายกุลธวัช สาลี,นางสาวฉวี ปิ่นทอม
0,ทุ่งสว่าง,15,138,11,751,12,1064,2,29,1,610
1,ธาตุ,16,185,528,1444,7,1902,5,10,4,50
2,บ่อแก้ว,19,129,17,1011,14,1601,2,8,0,23
3,เทศบาลตำบลบุสูง,22,255,15,1874,19,2448,36,14,6,124

In [ ]:
df_units_display.to_csv("constituency_units.csv",      index=False, encoding="utf-8-sig")
df_agg_constituency.to_csv("constituency_agg.csv",     index=False, encoding="utf-8-sig")
debug_df_constituency.to_csv("constituency_debug.csv", index=False, encoding="utf-8-sig")

print("\nSaved: constituency_units.csv")
print("Saved: constituency_agg.csv")
print("Saved: constituency_debug.csv")

files.download("constituency_units.csv")
files.download("constituency_agg.csv")
files.download("constituency_debug.csv")

Saved: constituency_units.csv
Saved: constituency_agg.csv
Saved: constituency_debug.csv

# Pipeline: ล่วงหน้านอกเขต

## Pre-Dataframe

In [14]:
CONSTITUENCY_CANDIDATES = {
    1: "นายสุเกษม เรืองนุช",
    2: "นายเนียม ผลบุญ",
    3: "นายธเนส เครือรัตน์",
    4: "นายวีรชัย จันทร์ดวงศรี",
    5: "นายสิริพงศ์ อังคสกุลเกียรติ",
    6: "นายสุรเดช นาจำปา",
    7: "นายคณีศร คำโสภา",
    8: "นายกุลธวัช สาลี",
    9: "นางสาวฉวี ปิ่นทอม",
}

CAND_COLS_EA = {num: f"ชื่อนามสกุลผู้สมัครหมายเลข{num}" for num in range(1, 10)}

print(f"Constituency candidates pre-loaded: {len(CONSTITUENCY_CANDIDATES)} คน")
for num, name in CONSTITUENCY_CANDIDATES.items():
    print(f"  {num}. {name}")

Constituency candidates pre-loaded: 9 คน
  1. นายสุเกษม เรืองนุช
  2. นายเนียม ผลบุญ
  3. นายธเนส เครือรัตน์
  4. นายวีรชัย จันทร์ดวงศรี
  5. นายสิริพงศ์ อังคสกุลเกียรติ
  6. นายสุรเดช นาจำปา
  7. นายคณีศร คำโสภา
  8. นายกุลธวัช สาลี
  9. นางสาวฉวี ปิ่นทอม

In [15]:
PARTY_NAMES_EA = [
    "ไทยทรัพย์ทวี",
    "เพื่อชาติไทย",
    "ใหม่",
    "มิติใหม่",
    "รวมใจไทย",
    "รวมไทยสร้างชาติ",
    "พลวัต",
    "ประชาธิปไตยใหม่",
    "เพื่อไทย",
    "ทางเลือกใหม่",
    "เศรษฐกิจ",
    "เสรีรวมไทย",
    "รวมพลังประชาชน",
    "ท้องที่ไทย",
    "อนาคตไทย",
    "พลังเพื่อไทย",
    "ไทยชนะ",
    "พลังสังคมใหม่",
    "สังคมประชาธิปไตยไทย",
    "ฟิวชัน",
    "ไทรวมพลัง",
    "ก้าวอิสระ",
    "ปวงชนไทย",
    "วิชช์นใหม่",
    "เพื่อชีวิตใหม่",
    "คลองไทย",
    "ประชาธิปัตย์",
    "ไทยก้าวหน้า",
    "ไทยภักดี",
    "แรงงานสร้างชาติ",
    "ประชากรไทย",
    "ครูไทยเพื่อประชาชน",
    "ประชาชาติ",
    "สร้างอนาคตไทย",
    "รักชาติ",
    "ไทยพร้อม",
    "ภูมิใจไทย",
    "พลังธรรมใหม่",
    "กรีน",
    "ไทยธรรม",
    "แผ่นดินธรรม",
    "กล้าธรรม",
    "พลังประชารัฐ",
    "โอกาสใหม่",
    "เป็นธรรม",
    "ประชาชน",
    "ประชาไทย",
    "ไทยสร้างไทย",
    "ไทยก้าวใหม่",
    "ประชาอาสาชาติ",
    "พร้อม",
    "เครือข่ายชาวนาแห่งประเทศไทย",
    "ไทยพิทักษ์ธรรม",
    "ความหวังใหม่",
    "ไทยรวมไทย",
    "เพื่อบ้านเมือง",
    "พลังไทยรักชาติ",
]

PARTY_INDEX_EA = {name: idx for idx, name in enumerate(PARTY_NAMES_EA)}
assert len(PARTY_NAMES_EA) == 57, f"Expected 57 parties, got {len(PARTY_NAMES_EA)}"
print(f"Pre-DataFrame ready: {len(PARTY_NAMES_EA)} พรรค")

Pre-DataFrame ready: 57 พรรค

## File Structure - Organization

In [16]:
import re as _re

early_voting_pdf_list = []

for entry in sorted(os.listdir(DATA_ROOT),
                    key=lambda x: int(_re.search(r'\d+', x).group()) if _re.search(r'\d+', x) else 0):
    entry_path = os.path.join(DATA_ROOT, entry)
    if not os.path.isdir(entry_path):
        continue
    if not entry.startswith('ชุดที่'):
        continue
    for fn in sorted(os.listdir(entry_path)):
        if fn.lower().endswith('.pdf'):
            early_voting_pdf_list.append((entry, os.path.join(entry_path, fn)))

print(f"Early-voting PDF sets found: {len(early_voting_pdf_list)}")
for label, path in early_voting_pdf_list:
    print(f"  {label}: {path}")

Early-voting PDF sets found: 11
  ชุดที่1: data/ชุดที่1/1.pdf
  ชุดที่2: data/ชุดที่2/2.pdf
  ชุดที่3: data/ชุดที่3/3.pdf
  ชุดที่4: data/ชุดที่4/4.pdf
  ชุดที่5: data/ชุดที่5/5.pdf
  ชุดที่6: data/ชุดที่6/6.pdf
  ชุดที่7: data/ชุดที่7/7.pdf
  ชุดที่8: data/ชุดที่8/8.pdf
  ชุดที่9: data/ชุดที่9/9.pdf
  ชุดที่10: data/ชุดที่10/10.pdf
  ชุดที่11: data/ชุดที่11/11.pdf

## Helper Function

In [ ]:
def extract_meta_ea_constituency(ocr_text):
    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = ocr_text.translate(thai_to_arabic)

    def grab(pattern):
        m = re.search(pattern, text)
        if not m:
            return None
        val = m.group(1).strip()
        return int(val) if val.isdigit() else None

    return {
        "received_cards"  : grab(r"ได้รับบัตรเลือกตั้ง.*?แบ่งเขต.*?ทั้งหมด\s*(\d+)"),
        "good_cards"      : grab(r"2\.1\s*บัตรดี\s*(\d+)"),
        "bad_cards"       : grab(r"2\.2\s*บัตรเสีย\s*(\d+)"),
        "no_vote_cards"   : grab(r"2\.3.*?ไม่เลือกผู้สมัครผู้ใด\s*(\d+)"),
    }


def extract_meta_ea_partylist(ocr_text):
    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = ocr_text.translate(thai_to_arabic)

    def grab(pattern):
        m = re.search(pattern, text)
        if not m:
            return None
        val = m.group(1).strip()
        return int(val) if val.isdigit() else None

    return {
        "received_cards"  : grab(r"ได้รับบัตรเลือกตั้ง.*?บัญชีรายชื่อ.*?ทั้งหมด\s*(\d+)"),
        "good_cards"      : grab(r"2\.1\s*บัตรดี\s*(\d+)"),
        "bad_cards"       : grab(r"2\.2\s*บัตรเสีย\s*(\d+)"),
        "no_vote_cards"   : grab(r"2\.3.*?ไม่เลือกบัญชีรายชื่อ.*?ใด\s*(\d+)"),
    }


def extract_ea_constituency_scores(ocr_text):
    soup = BeautifulSoup(ocr_text, "html.parser")
    scores = {}
    for table in soup.find_all("table"):
        for tr in table.find_all("tr")[1:]:  # skip header
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if len(cols) < 2:
                continue

            num_str = cols[0].translate(str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")).strip()
            if not re.match(r"^\d+$", num_str):
                continue
            cand_num = int(num_str)
            if cand_num < 1 or cand_num > 9:
                continue

            score = clean_score(cols[-1])
            scores[cand_num] = score if score is not None else 0
    return scores


def extract_ea_partylist_scores(ocr_text):
    soup = BeautifulSoup(ocr_text, "html.parser")
    scores = {}
    for table in soup.find_all("table"):
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if len(cols) < 3:
                continue
            if is_summary_row(cols):
                continue
            num_str = cols[0].translate(str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")).strip()
            if not re.match(r"^\d+$", num_str):
                continue
            party_num = int(num_str)
            if party_num < 1 or party_num > 57:
                continue
            score = clean_score(cols[2])
            scores[party_num - 1] = score if score is not None else 0  # 0-indexed
    return scores

## OCR

In [ ]:
EA_CONSTITUENCY_PAGES = {0, 1}   
EA_PARTYLIST_PAGES    = {2, 3, 4, 5} 

ea_con_rows    = []  
ea_party_rows  = []   
ea_debug_rows  = []   # debug

for set_label, pdf_path in early_voting_pdf_list:
    pdf_filename = os.path.basename(pdf_path)  # e.g. '3.pdf'

    print("\n" + "="*60)
    print(f" ชุด: {set_label}  |  PDF: {pdf_path}")
    print("="*60)

    pages = convert_from_path(pdf_path, 300)
    print(f" Total pages: {len(pages)}")

    ocr_results = {}

    for i, page in enumerate(pages):
        img_path = f"ea_page_{i}.jpg"
        page.save(img_path, "JPEG")
        try:
            result = typhoon_ocr.ocr_document(img_path)
            ocr_results[i] = result
            print(f"[Page {i}] Done")
        except Exception as e:
            print(f"[Page {i}] Error: {e}")
            ocr_results[i] = ""

    con_scores  = {}   
    con_meta    = {}
    con_pages_read = 0

    for pi in sorted(EA_CONSTITUENCY_PAGES):
        if pi not in ocr_results:
            continue
        ocr_text = ocr_results[pi]

        print("\n" + "-"*50)
        print(f"[Page {pi}] Raw (สส เขต):")
        print(ocr_text)

        if pi == 0:
            con_meta = extract_meta_ea_constituency(ocr_text)

        page_scores = extract_ea_constituency_scores(ocr_text)

        for k, v in page_scores.items():
            con_scores[k] = con_scores.get(k, 0) + v

        print(f"[Page {pi}] constituency scores read: {len(page_scores)} entries | {page_scores}")
        con_pages_read += 1

    con_row = {
        "source_pdf"   : pdf_path,
        "ชุด"          : set_label,
        **con_meta,
    }
    for num, col_name in CAND_COLS_EA.items():
        con_row[col_name] = con_scores.get(num, 0)
    ea_con_rows.append(con_row)

    party_scores = [0] * 57
    party_meta   = {}
    party_pages_read = 0

    for pi in sorted(EA_PARTYLIST_PAGES):
        if pi not in ocr_results:
            continue
        ocr_text = ocr_results[pi]

        print("\n" + "-"*50)
        print(f"[Page {pi}] Raw (บัญชีรายชื่อ):")
        print(ocr_text)

        if pi == 2:
            party_meta = extract_meta_ea_partylist(ocr_text)

        p_scores = extract_ea_partylist_scores(ocr_text)
        for idx, score in p_scores.items():
            party_scores[idx] += score

        print(f"[Page {pi}] party scores read: {len(p_scores)} entries")
        party_pages_read += 1

    total_party_score = sum(party_scores)
    party_status = "COMPLETE" if party_pages_read == 4 else f"only {party_pages_read}/4 pages read"

    print(f"\ncon_meta   : {con_meta}")
    print(f"party_meta : {party_meta}")
    print(f"total party score: {total_party_score} | {party_status}")

    party_row = {
        "source_pdf"   : pdf_path,
        "ชุด"          : set_label,
        **party_meta,
    }
    for idx, name in enumerate(PARTY_NAMES_EA):
        party_row[name] = party_scores[idx]
    ea_party_rows.append(party_row)

    # debug row
    ea_debug_rows.append({
        "ชุด"               : set_label,
        "source_pdf"        : pdf_path,
        "con_pages_read"    : con_pages_read,
        "con_scores_count"  : len(con_scores),
        "con_completeness"  : "yes" if len(con_scores) == 9 else f"{len(con_scores)}/9",
        "party_pages_read"  : party_pages_read,
        "party_total_score" : total_party_score,
        "party_completeness": party_status,
    })

print("\n" + "="*60)
print(f" TOTAL ชุด processed: {len(ea_con_rows)}")

============================================================
 ชุด: ชุดที่1  |  PDF: data/ชุดที่1/1.pdf
============================================================
 Total pages: 6
[Page 0] Done
[Page 1] Done
[Page 2] Done
[Page 3] Done
[Page 4] Done
[Page 5] Done

--------------------------------------------------
[Page 0] Raw (สส เขต):
ส.ส. ๕/๑๗

ชุดที่ ๑ (สีขาว) ส่งให้คณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง
ชุดที่ ๒ (สีเขียว) ปิดหน้าสถานที่นับคะแนนบัตรเลือกตั้ง
ชุดที่ ๓ (สีชมพู) ใส่ถุงวัสดุใสซึ่งบรรจุบัตรเลือกตั้งที่นับเป็นคะแนนแล้ว

รายงานผลการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักรแบบแบ่งเขตเลือกตั้ง
ณ สถานที่นับคะแนน (ชื่อสถานที่) หอประชุมคาบสมรรถ เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ

คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ชุดที่ 1 เขตเลือกตั้ง ที่ 1 จังหวัด ศรีสะเกษ ได้รับของใส่บัตรเลือกตั้งจาก บริษัท ไปรษณีย์ไทย จำกัด หรือผู้แทน หน่วยงาน หรือองค์กรที่คณะกรรมการการเลือกตั้งมอบหมาย จำนวน 750 ซอง และได้ตรวจนับจำนวน บัตรเลือกตั้งในซองใส่บัตรเลือกตั้งแล้ว มีจำนวน 750 บัตร จึงได้ดำเนินการนับคะแนนบัตรเลือกตั้ง นอกเขตเลือกตั้งและนอกราชอาณาจักรแบบแบ่งเขตเลือกตั้งเสร็จเรียบร้อยแล้ว ขอรายงานผลการนับคะแนน ดังนี้
๑. ได้รับบัตรเลือกตั้ง แบบแบ่งเขตเลือกตั้ง ทั้งหมด 750 บัตร
๒. คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ได้ดำเนินการนับ บัตรเลือกตั้งตามข้อ ๑ ปรากฏผล ดังนี้
๒.๑ บัตรดี 700 บัตร (เจ็ดร้อยสี่)
๒.๒ บัตรเสีย 15 บัตร (สิบห้าบัตร)
๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด 3 บัตร (สามสิบเก้า)

๓. จำนวนบัตรดี ตามข้อ ๒.๑ แยกเป็นคะแนนของผู้สมัครตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลข ประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัดพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>1</td><td>นายสังเกษม เรื่องานุช</td><td>ประชาธิปันธ์ใหม่</td><td>312 (สามร้อยสิบสอง)</td></tr><tr><td>2</td><td>นายเทียม พูลมูล</td><td>เพื่อไทย</td><td>8 (แปด)</td></tr><tr><td>3</td><td>นายสเนศ เครื่องรัตน์</td><td>ประชาธิปัตย์</td><td>94 (เก้าสิบสี่)</td></tr><tr><td>4</td><td>นายวีระชัย จันทร์ดวงศรี</td><td>ภูมิใจไทย</td><td>10 (สิบ)</td></tr><tr><td>5</td><td>นายสิริพงศ์ สังคลสกุลเกียรติ</td><td>ภูมิใจไทย</td><td>251 (สองร้อยห้าสิบเอ็ด)</td></tr><tr><td>6</td><td>นายสุรเดช นาฬาปา</td><td>กล้าธรรม</td><td>4 (สี่)</td></tr><tr><td>7</td><td>นายคลั่งศร คำโสภา</td><td>เศรษฐกิจ</td><td>9 (เก้า)</td></tr><tr><td>8</td><td>นายกฤษณ์ สาลี</td><td>รวมไทยสร้างชาติ</td><td>7 (เจ็ด)</td></tr></table>
[Page 0] constituency scores read: 8 entries | {1: 312, 2: 8, 3: 94, 4: 10, 5: 251, 6: 4, 7: 9, 8: 7}

--------------------------------------------------
[Page 1] Raw (สส เขต):
ส.ส. ๕/๑๗

<table><tr><td>หมายเลขประจำตัวผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัดพรรคการเมือง</td><td>ได้คะแนนตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>9</td><td>นางสาวณฐี ฟ้าหอม</td><td>พวงชนไทย</td><td>9 (เก้า)</td></tr><tr><td>10</td><td></td><td></td><td>(.)</td></tr><tr><td>11</td><td></td><td></td><td>(.)</td></tr><tr><td>12</td><td>ที่นับคะแนน (ชื่อสถานที่)</td><td></td><td>ที่ 1 สังหวัด นครราชสีมา</td></tr><tr><td>13</td><td></td><td></td><td>(.)</td></tr><tr><td>14</td><td>หรือองค์กรที่คณะกรรมการการเลือกตั้งมอบหมาย</td><td></td><td>(.)</td></tr><tr><td>15</td><td>ในของเสื้อบริษัท เด็กตั้งและนอกราชอาณาจักรแบบบัญชี</td><td></td><td>(.)</td></tr><tr><td>16</td><td>๑. ได้รับบัตรเลือกตั้ง แบบบัญชีรายชื่อ คณะกรรมการนับคะแนนบัตรเลือกตั้งเป็นของพรรคการเมือง</td><td>ซีอี ทั้งหมด</td><td>(.)</td></tr><tr><td>17</td><td>ตามข้อ ๑ ปรากฏผล ดังนี้</td><td></td><td>(.)</td></tr><tr><td>18</td><td>๒.๒ บัตรเลือกตั้ง</td><td></td><td>(.)</td></tr><tr><td>19</td><td>๒.๓ บัตรไม่เลือกบัญชีรายชื่อ</td><td>ยงพรรคการเมือง</td><td>(.)</td></tr><tr><td>20</td><td>จำนวนบัตรดี ตามข้อ ๒.๑ และเป็นของพรรคการเมือง</td><td></td><td>(.)</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>704 (เจ็ดร้อยสี่)</td></tr></table>

ประกาศ ณ วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2567
(ลงชื่อ) ประทานกรรมการนับคะแนนบัตรเลือกตั้ง
(นายสมพร อินเสนา)

(ลงชื่อ) กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.ณัฐภัสสร์ ทานวงศ์)

(ลงชื่อ) กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.ณัฐนันท์ ธนิสาระชาติ)

(ลงชื่อ) กรรมการนับคะแนนบัตรเลือกตั้ง
(นางนภา สุมาโท)

(ลงชื่อ) กรรมการนับคะแนนบัตรเลือกตั้ง
(นายสิรพล สวัสดิ์)

(ลงชื่อ) กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.ณัฐรินทร์ เจริญทอง)

(ลงชื่อ) กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.สุริยา วรรณพา)

หมายเหตุ
[Page 1] constituency scores read: 1 entries | {9: 9}

--------------------------------------------------
[Page 2] Raw (บัญชีรายชื่อ):
ส.ส. ๕/๑๗ (บช)

ขุดที่ ๑ (สีขาว) ส่งให้คณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง
ขุดที่ ๒ (สีเขียว) ปิดหน้าสถานที่นับคะแนนบัตรเลือกตั้ง
ขุดที่ ๓ (สีชมพู) ใส่ถุงวัสดุใส่ซึ่งบรรจุบัตรเลือกตั้งที่นับเป็นคะแนนแล้ว

รายงานผลการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักรแบบบัญชีรายชื่อ
ณ สถานที่นับคะแนน (ชื่อสถานที่) หอประชุมอาคมสโมสรฯ เขตเลือกตั้งที่ 1 จังหวัด ศรีสะเกษ

คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ชุดที่ 1 เขตเลือกตั้ง ที่ 1 จังหวัด ศรีสะเกษ ได้รับของใส่บัตรเลือกตั้งจาก บริษัท ไปรษณีย์ไทย จำกัด หรือผู้แทน หน่วยงาน หรือองค์กรที่คณะกรรมการการเลือกตั้งมอบหมาย จำนวน 790 ช่อง และได้ตรวจนับจำนวน บัตรเลือกตั้งในซองใส่บัตรเลือกตั้งแล้ว มีจำนวน 790 บัตร จึงได้ดำเนินการนับคะแนนบัตรเลือกตั้ง นอกเขตเลือกตั้งและนอกราชอาณาจักรแบบบัญชีรายชื่อเสร็จเรียบร้อยแล้ว ขอรายงานผลการนับคะแนน ดังนี้
๑. ได้รับบัตรเลือกตั้ง แบบบัญชีรายชื่อ ทั้งหมด 790 บัตร
๒. คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ได้ดำเนินการนับ บัตรเลือกตั้งตามข้อ ๑ ปรากฏผล ดังนี้
๒.๑ บัตรดี 790 บัตร (เจ็ดร้อยยี่สิบนำ)
๒.๒ บัตรเสีย 0 บัตร (เก้า)
๒.๓ บัตรที่ไม่เลือกบัญชีรายชื่อของพรรคการเมืองใด 16 บัตร (สามเณ)
๓. จำนวนบัตรดี ตามข้อ ๒.๑ แยกเป็นของพรรคการเมืองตามลำดับหมายเลขของบัญชีรายชื่อของ พรรคการเมือง

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>21</td><td>ไทยทรัพย์ทวี</td><td>1 (หนึ่ง)</td></tr><tr><td>22</td><td>เพื่อชาติไทย</td><td>4 (สี่)</td></tr><tr><td>23</td><td>ใหม่</td><td>2 (สอง)</td></tr><tr><td>24</td><td>มิติใหม่</td><td>- (-)</td></tr><tr><td>25</td><td>รวมใจไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>26</td><td>รวมไทยสร้างชาติ</td><td>6 (หก)</td></tr><tr><td>27</td><td>พลวัต</td><td>- (-)</td></tr><tr><td>38</td><td>ประชาธิปไตยใหม่</td><td>- (-)</td></tr></table>
[Page 2] party scores read: 8 entries

--------------------------------------------------
[Page 3] Raw (บัญชีรายชื่อ):
ส.ส. ๕/๑๗ (บช)

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>9</td><td>เพื่อไทย</td><td>99 (เก้าสิบเก้า)</td></tr><tr><td>10</td><td>ทางเลือกใหม่</td><td>2 (สอง)</td></tr><tr><td>11</td><td>เศรษฐกิจดี</td><td>9 (เก้า)</td></tr><tr><td>12</td><td>เสรีรวมไทย</td><td>2 (สอง)</td></tr><tr><td>13</td><td>รวมพลังประชาชน</td><td>2 (สอง)</td></tr><tr><td>14</td><td>ท้องที่ไทย</td><td>- ( - )</td></tr><tr><td>15</td><td>อนาคตไทย</td><td>- ( - )</td></tr><tr><td>16</td><td>พลังเพื่อไทย</td><td>- ( - )</td></tr><tr><td>17</td><td>ไทยชนะ</td><td>- ( - )</td></tr><tr><td>18</td><td>พลังสังคมใหม่</td><td>- ( - )</td></tr><tr><td>19</td><td>สังคมประชาธิปไตยไทย</td><td>- ( - )</td></tr><tr><td>20</td><td>ฟิวชัน รวม</td><td>- ( - )</td></tr><tr><td>21</td><td>ไทรวมพลัง ภูมิใจ</td><td>1 (หนึ่ง)</td></tr><tr><td>22</td><td>ก้าวอิสระ</td><td>- ( - )</td></tr><tr><td>23</td><td>ปวงชนไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>24</td><td>วิชชั่นใหม่</td><td>- ( - )</td></tr><tr><td>25</td><td>เพื่อชีวิตใหม่</td><td>- ( - )</td></tr><tr><td>26</td><td>คลองไทย</td><td>- ( - )</td></tr><tr><td>27</td><td>ประชาธิปัตย์</td><td>12 (สิบสอง)</td></tr><tr><td>28</td><td>ไทยก้าวหน้า ชาติ</td><td>1 (หนึ่ง)</td></tr><tr><td>29</td><td>ไทยภักดี</td><td>7 (เจ็ด)</td></tr><tr><td>30</td><td>แรงงานสร้างชาติ เห่งประเทศไทย</td><td>- ( - )</td></tr></table>
[Page 3] party scores read: 22 entries

--------------------------------------------------
[Page 4] Raw (บัญชีรายชื่อ):
ส.ส. ๕/๑๗ (บช)

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>31</td><td>ประชากรไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>32</td><td>ครูไทยเพื่อประชาชน</td><td>1 (หนึ่ง)</td></tr><tr><td>33</td><td>ประชาชาติ</td><td>- ( - )</td></tr><tr><td>34</td><td>สร้างอนาคตไทย</td><td>- ( - )</td></tr><tr><td>35</td><td>รักชาติ</td><td>- ( - )</td></tr><tr><td>36</td><td>ไทยพร้อม</td><td>- ( - )</td></tr><tr><td>37</td><td>ภูมิใจไทย เดือน กุมภาพันธ์</td><td>125 (สองร้อยยี่สิบห้า)</td></tr><tr><td>38</td><td>พลังธรรมใหม่</td><td>- ( - )</td></tr><tr><td>39</td><td>กรีน</td><td>- ( - )</td></tr><tr><td>40</td><td>ไทยธรรม แน่นบัตรเลือกตั้ง (ลงชื่อ)</td><td>- (กรรมการนับคะแนนบัตรเลือกตั้ง)</td></tr><tr><td>41</td><td>แผ่นดินธรรม</td><td>- ( - )</td></tr><tr><td>42</td><td>กล้าธรรม</td><td>- ( - )</td></tr><tr><td>43</td><td>พลังประชารัฐ</td><td>1 (หนึ่ง)</td></tr><tr><td>44</td><td>โอกาสใหม่</td><td>- ( - )</td></tr><tr><td>45</td><td>เป็นธรรม แน่นบัตรเลือกตั้ง (ลงชื่อ)</td><td>- (กรรมการนับคะแนนบัตรเลือกตั้ง)</td></tr><tr><td>46</td><td>ประชาชน</td><td>439 (สี่ร้อยสามสิบเก้า)</td></tr><tr><td>47</td><td>ประชาไทย</td><td>- ( - )</td></tr><tr><td>48</td><td>ไทยสร้างไทย</td><td>5 (ห้า)</td></tr><tr><td>49</td><td>ไทยก้าวใหม่</td><td>2 (สอง)</td></tr><tr><td>50</td><td>ประชาอาสาชาติ</td><td>- ( - )</td></tr><tr><td>51</td><td>พร้อม</td><td>1 (หนึ่ง)</td></tr><tr><td>52</td><td>เครือข่ายชาวนาแห่งประเทศไทย</td><td>- ( - )</td></tr></table>
[Page 4] party scores read: 22 entries

--------------------------------------------------
[Page 5] Raw (บัญชีรายชื่อ):
ส.ส. ๕/๑๗ (บช)

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>53</td><td>ไทยพิทักษ์ธรรม</td><td>-</td></tr><tr><td>54</td><td>ความหวังใหม่</td><td>-</td></tr><tr><td>55</td><td>ไทยรวมไทย</td><td>-</td></tr><tr><td>56</td><td>เพื่อบ้านเมือง</td><td>-</td></tr><tr><td>57</td><td>พลังไทยรักชาติ</td><td>-</td></tr><tr><td colspan="2">รวมคะแนนทั้งสิ้น</td><td>990 เจ็ดร้อยเก้าสิบ</td></tr></table>

ประกาศ ณ วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569

(ลงชื่อ)  ประธานกรรมการนับคะแนนบัตรเลือกตั้ง
(นายสมชาย อินลาภ)
(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นายณัฐพงษ์ คานวงศ์)
(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นางสาวปรียา สุมาโท)
(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นายธีระพล สนโสดา)
(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นายธีระพล แจ่มใส)
(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นายพิชย์รินทร์ เจริญพัฒน์)
(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นายสุริยา ไตรกระถาง)

หมายเหตุ

(ลงชื่อ)  กรรมการประจำหน่วยเลือกตั้ง
(นายธีระพล สนโสดา)
(ลงชื่อ)  กรรมการประจำหน่วยเลือกตั้ง
(นายพิชัยรินทร์ เจริญพัฒน์)
(ลงชื่อ)  กรรมการประจำหน่วยเลือกตั้ง
(นายธีระพล แจ่มใส)
[Page 5] party scores read: 5 entries

con_meta   : {'received_cards': 750, 'good_cards': 700, 'bad_cards': 15, 'no_vote_cards': 3}
party_meta : {'received_cards': 790, 'good_cards': 790, 'bad_cards': 0, 'no_vote_cards': 16}
total party score: 725 | COMPLETE

============================================================
 ชุด: ชุดที่2  |  PDF: data/ชุดที่2/2.pdf
============================================================
 Total pages: 6
[Page 0] Done
[Page 1] Done
[Page 2] Done
[Page 3] Done
[Page 4] Done
[Page 5] Done

--------------------------------------------------
[Page 0] Raw (สส เขต):
ส.ส. ๕/๑๗

ชุดที่ ๑ (สีขาว) ส่งให้คณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง
ชุดที่ ๒ (สีเขียว) ปิดหน้าสถานที่นับคะแนนบัตรเลือกตั้ง
ชุดที่ ๓ (สีชมพู) ใส่ถุงวัสดุใส่ซึ่งบรรจุบัตรเลือกตั้งที่นับเป็นคะแนนแล้ว

รายงานผลการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักรแบบแบ่งเขตเลือกตั้ง
ณ สถานที่นับคะแนน (ชื่อสถานที่) หอประชุมลาดพร้าว ถนนพหลโยธิน เขตบางรัก กรุงเทพมหานคร
คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ชุดที่ 2 เขตเลือกตั้ง ที่ 1 จังหวัด พระนคร
ได้รับซองใส่บัตรเลือกตั้งจาก บริษัท ไปรษณีย์ไทย จำกัด หรือผู้แทน หน่วยงาน หรือองค์กรที่คณะกรรมการการเลือกตั้งมอบหมาย จำนวน 750 ซอง และได้ตรวจนับจำนวน บัตรเลือกตั้งในซองใส่บัตรเลือกตั้งแล้ว มีจำนวน 750 บัตร จึงได้ดำเนินการนับคะแนนบัตรเลือกตั้ง นอกเขตเลือกตั้งและนอกราชอาณาจักรแบบแบ่งเขตเลือกตั้งเสร็จเรียบร้อยแล้ว ขอรายงานผลการนับคะแนน ดังนี้
๑. ได้รับบัตรเลือกตั้ง แบบแบ่งเขตเลือกตั้ง ทั้งหมด 750 บัตร
๒. คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ได้ดำเนินการนับ บัตรเลือกตั้งตามข้อ ๑ ปรากฏผล ดังนี้
๒.๑ บัตรดี 707 บัตร (เจ็ดร้อยห้าสิบ)
๒.๒ บัตรเสีย 8 บัตร (แปด)
๒.๓ บัตรที่ไม่เลือกผู้สมัครผู้ใด 35 บัตร (สามสิบห้า)

๓. จำนวนบัตรดี ตามข้อ ๒.๑ แยกเป็นคะแนนของผู้สมัครตามลำดับหมายเลขประจำตัวผู้สมัคร

<table><tr><td>หมายเลข ประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัดพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>1</td><td>นายสุราเมฆ เรียงบุญ</td><td>ประชาธิปัตย์</td><td>299 (สองร้อยเก้าสิบเก้า)</td></tr><tr><td>2</td><td>นายเพียร พลมุต</td><td>ประชาธิปัตย์ใหม่</td><td>9 (เก้า)</td></tr><tr><td>3</td><td>นายธนพล เจริญรัตน์</td><td>เพื่อไทย</td><td>138 (หนึ่งร้อยสามสิบแปด)</td></tr><tr><td>4</td><td>นางปริณัย จันทร์วงศ์</td><td>ประชาธิปัตย์</td><td>3 (สาม)</td></tr><tr><td>5</td><td>นายสร้างศรี คงคลอดเพียร</td><td>ภูมิใจไทย</td><td>242 (สองร้อยสี่สิบสอง)</td></tr><tr><td>6</td><td>นายสุธาเดช นาวาปา</td><td>กล้าธรรม</td><td>4 (สี่)</td></tr><tr><td>7</td><td>นายอดุลย์ คำโสภา</td><td>เพิ่มรัฐใจ</td><td>3 (สาม)</td></tr><tr><td>8</td><td>นายอุลตร์ สาลี</td><td>รวมไทยสร้างชาติ</td><td>3 (สาม)</td></tr></table>
[Page 0] constituency scores read: 8 entries | {1: 299, 2: 9, 3: 138, 4: 3, 5: 242, 6: 4, 7: 3, 8: 3}

--------------------------------------------------
[Page 1] Raw (สส เขต):
ส.ส. ๕/๑๗

<table><tr><td>หมายเลข ประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัดพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>9</td><td>นายภควาลย์ มีนทอง</td><td>พรรษาไทย</td><td>6 (หก)</td></tr><tr><td>10</td><td></td><td></td><td>( )</td></tr><tr><td>11</td><td></td><td></td><td>( )</td></tr><tr><td>12</td><td></td><td></td><td>( )</td></tr><tr><td>13</td><td>คณะกรรมการนับคะแนนบัตรเลือกตั้ง</td><td>นอกเขตเลือกตั้งและนอกเขตเลือกตั้ง</td><td>( )</td></tr><tr><td>14</td><td>หรือองค์กรที่คณะกรรมการการเลือกตั้งมอบหมาย</td><td>จำนวน 2</td><td>(สอง และได้ตรวจบันทึก)</td></tr><tr><td>15</td><td>สำนักงานเลือกตั้งและกองการอาญาจักรแบบบัญชี</td><td>หรือบริษัทรับรองข้อเท็จจริง</td><td>(การนับคะแนนบัตรเลือกตั้ง)</td></tr><tr><td>16</td><td>๑. ได้รับบัตรเลือกตั้ง แบบบัญชีรายชื่อ ทั้งหมด 750 บัตร<br/>๒. คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งแล้ว</td><td></td><td>( )</td></tr><tr><td>17</td><td>ตามข้อ ๑ ปรากฏผล ดังนี้</td><td></td><td>( )</td></tr><tr><td>18</td><td>๒.๒ บัตรเสีย</td><td></td><td>( )</td></tr><tr><td>19</td><td>๒.๓ บัตรที่ไม่เลือกบัญชีรายชื่อของพรรคการเมืองใด</td><td></td><td>( )</td></tr><tr><td>20</td><td>จำนวนบัตรที่ ตามข้อ ๒.๑ แก่เป็นของพรรคการเมืองใด</td><td></td><td>( )</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>700 (เจ็ดร้อยบาทถ้วน)</td></tr></table>

ประกาศ ณ วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569
(ลงชื่อ) ลายเซ็น ประธานกรรมการนับคะแนนบัตรเลือกตั้ง
(นางสาวกาญจนา มีดีพมาน)
(ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง (ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง
(นางสาวจิราพร เรียง)
(ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง (ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง
(นางสาวศิริณัฐ ฉะเชิงเทรา)
(ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง (ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง
(นายสุชาดา ไพบูลย์ธรรม)
(ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง (ลงชื่อ) ลายเซ็น กรรมการนับคะแนนบัตรเลือกตั้ง
(นายพิชชาพร อินทโชติ)

หมายเหตุ
8 ประชาธิปไตยใหม่
[Page 1] constituency scores read: 1 entries | {9: 6}

--------------------------------------------------
[Page 2] Raw (บัญชีรายชื่อ):
ส.ส. ๕/๑๗ (บช)

ขุดที่ ๑ (สีขาว) ส่งให้คณะกรรมการการเลือกตั้งประจำเขตเลือกตั้ง
ขุดที่ ๒ (สีเขียว) ปิดหน้าสถานที่นับคะแนนบัตรเลือกตั้ง
ขุดที่ ๓ (สีชมพู) ใส่ถุงวัสดุใส่ซึ่งบรรจุบัตรเลือกตั้งที่นับเป็นคะแนนแล้ว

รายงานผลการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักรแบบบัญชีรายชื่อ
ณ สถานที่นับคะแนน (ชื่อสถานที่) หอประชุมสภาราษฎร์มหาราชินิยมเขตเลือกตั้งที่ 1 จังหวัดศรีสะเกษ
(ทางหลวงหมายเลข 209 ต.ศรีสะเกษ อ.ศรีสะเกษ จ.ศรีสะเกษ)

คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ชุดที่ ๕ เขตเลือกตั้ง ที่ 1 จังหวัดศรีสะเกษ ได้รับของใส่บัตรเลือกตั้งจาก บริษัท ไปรษณีย์ไทย จำกัด หรือผู้แทน หน่วยงาน หรือองค์กรที่คณะกรรมการการเลือกตั้งมอบหมาย จำนวน 750 ช่อง และได้ตรวจนับจำนวน บัตรเลือกตั้งในซองใส่บัตรเลือกตั้งแล้ว มีจำนวน 750 บัตร จึงได้ดำเนินการนับคะแนนบัตรเลือกตั้ง นอกเขตเลือกตั้งและนอกราชอาณาจักรแบบบัญชีรายชื่อเสร็จเรียบร้อยแล้ว ขอรายงานผลการนับคะแนน ดังนี้
๑. ได้รับบัตรเลือกตั้ง แบบบัญชีรายชื่อ ทั้งหมด 750 บัตร
๒. คณะกรรมการนับคะแนนบัตรเลือกตั้งนอกเขตเลือกตั้งและนอกราชอาณาจักร ได้ดำเนินการนับ บัตรเลือกตั้งตามข้อ ๑ ปรากฏผล ดังนี้
๒.๑ บัตรดี 756 บัตร (เจ็ดร้อยห้าสิบหก)
๒.๒ บัตรเสีย 4 บัตร (๔)
๒.๓ บัตรที่ไม่เลือกบัญชีรายชื่อของพรรคการเมืองใด 20 บัตร (ยี่สิบ)
๓. จำนวนบัตรดี ตามข้อ ๒.๑ แยกเป็นของพรรคการเมืองตามลำดับหมายเลขของบัญชีรายชื่อของ พรรคการเมือง

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>21</td><td>ไทยทรัพย์ทวี</td><td>1 (หนึ่ง)</td></tr><tr><td>22</td><td>เพื่อชาติไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>23</td><td>ใหม่</td><td>5 (ห้า)</td></tr><tr><td>24</td><td>มิติใหม่</td><td>2 (สอง)</td></tr><tr><td>25</td><td>รวมใจไทย</td><td>7 (เจ็ด)</td></tr><tr><td>26</td><td>รวมไทยสร้างชาติ</td><td>8 (แปด)</td></tr><tr><td>27</td><td>พลวัต</td><td>1 (หนึ่ง)</td></tr><tr><td>38</td><td>ประชาธิปไตยใหม่</td><td>1 (หนึ่ง)</td></tr></table>
[Page 2] party scores read: 8 entries

--------------------------------------------------
[Page 3] Raw (บัญชีรายชื่อ):
ส.ส. ๕/๑๗ (บช)

<table><tr><td>หมายเลขของบัญชีรายชื่อ<br/>ของพรรคการเมือง</td><td>ชื่อพรรคการเมือง</td><td>ได้คะแนน<br/>ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>9</td><td>เพื่อไทย</td><td>112 (หนึ่งร้อยสิบสอง)</td></tr><tr><td>10</td><td>ทางเลือกใหม่</td><td>2 (สอง)</td></tr><tr><td>11</td><td>เศรษฐกิจ</td><td>8 (แปด)</td></tr><tr><td>12</td><td>เสรีรวมไทย</td><td>2 (สอง)</td></tr><tr><td>13</td><td>รวมพลังประชาชน</td><td>2 (สอง)</td></tr><tr><td>14</td><td>ท้องที่ไทย</td><td>0 (ศูนย์)</td></tr><tr><td>15</td><td>อนาคตไทย</td><td>0 (ศูนย์)</td></tr><tr><td>16</td><td>พลังเพื่อไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>17</td><td>ไทยชนะ</td><td>0 (ศูนย์)</td></tr><tr><td>18</td><td>พลังสังคมใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>19</td><td>สังคมประชาธิปไตยไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>20</td><td>ฟิวชัน</td><td>0 (ศูนย์)</td></tr><tr><td>21</td><td>ไทรวมพลัง</td><td>1 (หนึ่ง)</td></tr><tr><td>22</td><td>ก้าวอิสระ</td><td>0 (ศูนย์)</td></tr><tr><td>23</td><td>ปวงชนไทย</td><td>1 (หนึ่ง)</td></tr><tr><td>24</td><td>วิชชั่นใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>25</td><td>เพื่อชีวิตใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>26</td><td>คลองไทย</td><td>0 (ศูนย์)</td></tr><tr><td>27</td><td>ประชาธิปัตย์</td><td>7 (เจ็ด)</td></tr><tr><td>28</td><td>ไทยก้าวหน้าชาติ</td><td>1 (หนึ่ง)</td></tr><tr><td>29</td><td>ไทยภักดี</td><td>2 (สอง)</td></tr><tr><td>30</td><td>แรงงานสร้างชาติแห่งประเทศไทย</td><td>0 (ศูนย์)</td></tr></table>
[Page 3] party scores read: 22 entries

--------------------------------------------------
[Page 4] Raw (บัญชีรายชื่อ):
ส.ส. ๕/๑๗ (บช)


## Export DataFrame

In [19]:
df_ea_constituency = pd.DataFrame(ea_con_rows)

rename_map_ea = {f"ชื่อนามสกุลผู้สมัครหมายเลข{num}": CONSTITUENCY_CANDIDATES[num]
                 for num in range(1, 10)}
df_ea_con_display = df_ea_constituency.rename(columns=rename_map_ea)

print("=== df_ea_constituency (สส เขต ล่วงหน้านอกเขต) ===")
print(f"Rows: {len(df_ea_constituency)}")
display(df_ea_con_display)

=== df_ea_constituency (สส เขต ล่วงหน้านอกเขต) ===
Rows: 11

,source_pdf,ชุด,received_cards,good_cards,bad_cards,no_vote_cards,นายสุเกษม เรืองนุช,นายเนียม ผลบุญ,นายธเนส เครือรัตน์,นายวีรชัย จันทร์ดวงศรี,นายสิริพงศ์ อังคสกุลเกียรติ,นายสุรเดช นาจำปา,นายคณีศร คำโสภา,นายกุลธวัช สาลี,นางสาวฉวี ปิ่นทอม
0,data/ชุดที่1/1.pdf,ชุดที่1,750,700,15,3,312,8,94,10,251,4,9,7,9
1,data/ชุดที่2/2.pdf,ชุดที่2,750,707,8,35,299,9,138,3,242,4,3,3,6
2,data/ชุดที่3/3.pdf,ชุดที่3,750,707,10,33,307,8,115,3,256,4,8,1,5
3,data/ชุดที่4/4.pdf,ชุดที่4,350,705,15,30,372,8,16,5,200,5,5,0,0
4,data/ชุดที่5/5.pdf,ชุดที่5,750,701,13,36,310,10,112,6,243,2,8,3,7
5,data/ชุดที่6/6.pdf,ชุดที่6,750,716,6,28,714,8,107,6,260,9,9,6,9
6,data/ชุดที่7/7.pdf,ชุดที่7,750,710,7,33,329,13,101,7,229,5,12,8,10
7,data/ชุดที่8/8.pdf,ชุดที่8,750,696,17,35,318,8,97,12,240,4,5,6,8
8,data/ชุดที่9/9.pdf,ชุดที่9,750,706,8,36,319,8,103,3,238,6,13,4,12
9,data/ชุดที่10/10.pdf,ชุดที่10,750,710,10,26,309,7,104,9,256,4,8,5,11
10,data/ชุดที่11/11.pdf,ชุดที่11,593,566,11,16,286,5,74,10,172,3,11,1,4

In [20]:
df_ea_partylist = pd.DataFrame(ea_party_rows)

print("=== df_ea_partylist (บัญชีรายชื่อ ล่วงหน้านอกเขต) ===")
print(f"Rows: {len(df_ea_partylist)}")
display(df_ea_partylist)

=== df_ea_partylist (บัญชีรายชื่อ ล่วงหน้านอกเขต) ===
Rows: 11

,source_pdf,ชุด,received_cards,good_cards,bad_cards,no_vote_cards,ไทยทรัพย์ทวี,เพื่อชาติไทย,ใหม่,มิติใหม่,...,ไทยสร้างไทย,ไทยก้าวใหม่,ประชาอาสาชาติ,พร้อม,เครือข่ายชาวนาแห่งประเทศไทย,ไทยพิทักษ์ธรรม,ความหวังใหม่,ไทยรวมไทย,เพื่อบ้านเมือง,พลังไทยรักชาติ
0,data/ชุดที่1/1.pdf,ชุดที่1,790,790,0.0,16.0,0,0,0,0,...,5,2,0,1,0,0,0,0,0,0
1,data/ชุดที่2/2.pdf,ชุดที่2,750,756,4.0,20.0,0,0,0,0,...,1,5,0,1,0,0,0,0,0,0
2,data/ชุดที่3/3.pdf,ชุดที่3,750,728,7.0,15.0,0,0,0,0,...,5,2,0,0,0,0,0,0,0,1
3,data/ชุดที่4/4.pdf,ชุดที่4,350,330,5.0,14.0,0,2,0,0,...,3,1,0,0,0,0,0,0,0,0
4,data/ชุดที่5/5.pdf,ชุดที่5,731,9,10.0,NaN,0,6,3,0,...,8,2,0,4,0,0,0,0,0,0
5,data/ชุดที่6/6.pdf,ชุดที่6,750,720,7.0,23.0,1,9,1,0,...,5,1,0,0,0,0,0,0,1,1
6,data/ชุดที่7/7.pdf,ชุดที่7,750,726,4.0,20.0,1,7,0,0,...,3,5,0,0,0,0,0,6,0,0
7,data/ชุดที่8/8.pdf,ชุดที่8,750,924,NaN,15.0,0,0,0,0,...,3,2,0,0,0,0,0,1,0,0
8,data/ชุดที่9/9.pdf,ชุดที่9,750,715,6.0,29.0,0,0,0,0,...,3,3,0,0,0,0,0,0,0,0
9,data/ชุดที่10/10.pdf,ชุดที่10,750,720,16.0,14.0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
10,data/ชุดที่11/11.pdf,ชุดที่11,593591,570,28.0,14.0,442,1,0,0,...,1,2,0,0,0,0,0,0,0,0

In [21]:
df_ea_debug = pd.DataFrame(ea_debug_rows)
print("=== debug ===")
display(df_ea_debug)

=== debug ===

,ชุด,source_pdf,con_pages_read,con_scores_count,con_completeness,party_pages_read,party_total_score,party_completeness
0,ชุดที่1,data/ชุดที่1/1.pdf,2,9,yes,4,725,COMPLETE
1,ชุดที่2,data/ชุดที่2/2.pdf,2,9,yes,4,728,COMPLETE
2,ชุดที่3,data/ชุดที่3/3.pdf,2,9,yes,4,734,COMPLETE
3,ชุดที่4,data/ชุดที่4/4.pdf,2,9,yes,4,511,COMPLETE
4,ชุดที่5,data/ชุดที่5/5.pdf,2,9,yes,4,749,COMPLETE
5,ชุดที่6,data/ชุดที่6/6.pdf,2,9,yes,4,637,COMPLETE
6,ชุดที่7,data/ชุดที่7/7.pdf,2,9,yes,4,319,COMPLETE
7,ชุดที่8,data/ชุดที่8/8.pdf,2,9,yes,4,724,COMPLETE
8,ชุดที่9,data/ชุดที่9/9.pdf,2,9,yes,4,715,COMPLETE
9,ชุดที่10,data/ชุดที่10/10.pdf,2,9,yes,4,720,COMPLETE
10,ชุดที่11,data/ชุดที่11/11.pdf,2,9,yes,4,1010,COMPLETE

In [22]:
df_ea_con_display.to_csv("early_voting_constituency.csv",  index=False, encoding="utf-8-sig")
df_ea_partylist.to_csv("early_voting_partylist.csv",        index=False, encoding="utf-8-sig")
df_ea_debug.to_csv("early_voting_debug.csv",                index=False, encoding="utf-8-sig")

print("Saved: early_voting_constituency.csv")
print("Saved: early_voting_partylist.csv")
print("Saved: early_voting_debug.csv")

Saved: early_voting_constituency.csv
Saved: early_voting_partylist.csv
Saved: early_voting_debug.csv

In [23]:
from google.colab import files
files.download("early_voting_constituency.csv")
files.download("early_voting_partylist.csv")
files.download("early_voting_debug.csv")

# Pipeline: ล่วงหน้าในเขต

In [25]:
import os, zipfile
from google.colab import files
from pdf2image import convert_from_path
import typhoon_ocr
from bs4 import BeautifulSoup

uploaded = files.upload()

for fname, data in uploaded.items():
    with open(fname, 'wb') as f:
        f.write(data)

    pages = convert_from_path(fname, 300)
    img_path = "debug_page_0.jpg"
    pages[0].save(img_path, "JPEG")

    ocr_text = typhoon_ocr.ocr_document(img_path)
    print(ocr_text)
    print("="*60)

    soup = BeautifulSoup(ocr_text, "html.parser")
    for td in soup.find_all("td"):
        if "รวมคะแนนทั้งสิ้น" in td.get_text():
            tr = td.find_parent("tr")
            print("พบ 'รวมคะแนนทั้งสิ้น':", tr.get_text(separator=" | ", strip=True))

Saving ในเขต.pdf to ในเขต.pdf
ส.ส. ๕/๑๖ (บช)

<table><tr><td>หมายเลขของบัญชีรายชื่อ ของพรรคการเมือง</td><td>ชื่อพรรคการเมือง</td><td>ได้คะแนน ตัวเลข (อารบิก) / ตัวอักษร</td></tr><tr><td>53</td><td>ไทยพิทักษ์ธรรม</td><td>0 (ศูนย์)</td></tr><tr><td>54</td><td>ความหวังใหม่</td><td>0 (ศูนย์)</td></tr><tr><td>55</td><td>ไทยรวมไทย</td><td>0 (ศูนย์)</td></tr><tr><td>56</td><td>เพื่อบ้านเมือง</td><td>0 (ศูนย์)</td></tr><tr><td>57</td><td>พลังไทยรักชาติ</td><td>0 (ศูนย์)</td></tr><tr><td colspan="2">รวมคะแนนทั้งสิ้น</td><td>13 (ศูนย์)</td></tr></table>

ประกาศ ณ วันที่ 8 เดือน กุมภาพันธ์ พ.ศ. 2569

(ลงชื่อ)  ประธานกรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.ชัยชลลี สำภา)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.ปิยาภรณ์ ส่งหันชม)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นายเดชณรงค์ คำสว่าง)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.พญรี ศรีสมุทร)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(นางอาญา สุมาลี)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.ศิวาพร โพลพิมพ์)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.ปกรณ์ ศิริพันธ์)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.นาฬิน หาญอรุณ)

(ลงชื่อ)  กรรมการนับคะแนนบัตรเลือกตั้ง
(น.ส.นันทนา สร้างทอง)

หมายเหตุ
============================================================
พบ 'รวมคะแนนทั้งสิ้น': รวมคะแนนทั้งสิ้น | 13 (ศูนย์)